### ISSUE TITLE
Causing issues with fulltextsearch

### ISSUE THREAD

**Issue by jurgenhaas** [nextcloud/deck#1070]
Both deck and fulltextsearch are using the latest versions of their respective plugins. When I run the index on the CLI the following error occurs on every single installation:

```
TypeError: Argument 1 passed to OC\FullTextSearch\Model\IndexDocument::setContent() must be of the type string, null given, called in /var/www/nextcloud/lakedrops/apps/deck/lib/Service/FullTextSearchService.php on line 182 and defined in /var/www/nextcloud/lakedrops/lib/private/FullTextSearch/Model/IndexDocument.php:477
Stack trace:
#0 /var/www/nextcloud/lakedrops/apps/deck/lib/Service/FullTextSearchService.php(182): OC\FullTextSearch\Model\IndexDocument->setContent(NULL)
#1 /var/www/nextcloud/lakedrops/apps/deck/lib/Provider/DeckProvider.php(187): OCA\Deck\Service\FullTextSearchService->fillIndexDocument(Object(OC\FullTextSearch\Model\IndexDocument))
#2 /var/www/nextcloud/lakedrops/apps/fulltextsearch/lib/Service/IndexService.php(325): OCA\Deck\Provider\DeckProvider->fillIndexDocument(Object(OC\FullTextSearch\Model\IndexDocument))
#3 /var/www/nextcloud/lakedrops/apps/fulltextsearch/lib/Service/IndexService.php(205): OCA\FullTextSearch\Service\IndexService->indexDocuments(Object(OCA\FullTextSearch_ElasticSearch\Platform\ElasticSearchPlatform), Object(OCA\Deck\Provider\DeckProvider), Array, Object(OCA\FullTextSearch\Model\IndexOptions))
#4 /var/www/nextcloud/lakedrops/apps/fulltextsearch/lib/Command/Index.php(409): OCA\FullTextSearch\Service\IndexService->indexProviderContentFromUser(Object(OCA\FullTextSearch_ElasticSearch\Platform\ElasticSearchPlatform), Object(OCA\Deck\Provider\DeckProvider), 'jurgenhaas', Object(OCA\FullTextSearch\Model\IndexOptions))
#5 /var/www/nextcloud/lakedrops/apps/fulltextsearch/lib/Command/Index.php(273): OCA\FullTextSearch\Command\Index->indexProvider(Object(OCA\Deck\Provider\DeckProvider), Object(OCA\FullTextSearch\Model\IndexOptions))
#6 /var/www/nextcloud/lakedrops/3rdparty/symfony/console/Command/Command.php(255): OCA\FullTextSearch\Command\Index->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#7 /var/www/nextcloud/lakedrops/core/Command/Base.php(166): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#8 /var/www/nextcloud/lakedrops/3rdparty/symfony/console/Application.php(901): OC\Core\Command\Base->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#9 /var/www/nextcloud/lakedrops/3rdparty/symfony/console/Application.php(262): Symfony\Component\Console\Application->doRunCommand(Object(OCA\FullTextSearch\Command\Index), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#10 /var/www/nextcloud/lakedrops/3rdparty/symfony/console/Application.php(145): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#11 /var/www/nextcloud/lakedrops/lib/private/Console/Application.php(213): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#12 /var/www/nextcloud/lakedrops/console.php(97): OC\Console\Application->run()
#13 /var/www/nextcloud/lakedrops/occ(11): require_once('/var/www/nextcl...')
#14 {main}⏎                                                                         
```

At the beginning I thought it might be a content issue and fulltextsearch were doing something wrong. But it turned out, even with "empty" installations, as soon as deck gets enabled we see this exception.

Unfortunately I couldn't find out more details, even with verbode mode, I don't get more information.

So I hope you can find out with the stack trace what's going wrong.

**Comment by level420** [comment]
I can confirm this with with 

- Deck 0.6.2
- Full text search 1.33
- Full text search - Elasticsearch Platform 1.3.1
- Full text search - Files 1.3.2
- nextcloud 16.0.1.1 as fpm from docker.id
- elasticsearch docker image 6.5.4 from docker.elastic.co/elasticsearch/elasticsearch with current ingest-attachmen plugin

**Comment by level420** [comment]
Updated elasticsearch docker image to 7.1.1 from docker.io with current ingest attachment plugin with the same result.

**Comment by level420** [comment]
might be solved in the 0.6.3 release via this PR: https://github.com/nextcloud/deck/pull/1049
See also https://github.com/nextcloud/fulltextsearch/issues/498

**Comment by level420** [comment]
@juliushaertl I've seen that milestone 0.6.3 is complete. what is the scheduled release date for 0.6.3?
this bug prevents indexing completely.

**Comment by juliushaertl** [comment]
Sorry for the delay on this, I'll prepare a new release next week.

**Comment by e-alfred** [comment]
Having the same issue, hopefully @juliushaertl you can release a new version of Deck soon.

**Comment by juliushaertl** [comment]
Fix merged, closeing the issue
