### ISSUE TITLE
Tracekback shown using occ deck:export (deck 0.6.6)

### ISSUE THREAD

**Issue by mcassaniti** [nextcloud/deck#1303]
**Describe the bug**
When using `occ deck:export <user>`, I get a traceback.

**Steps To Reproduce**
`occ deck:export <user>`

**Expected behavior**
Export succeeds

**Traceback**
```
An unhandled exception has been thrown:
TypeError: Argument 1 passed to OC\Group\Manager::getUserGroupIds() must implement interface OCP\IUser, null given, called in /var/lib/nextcloud/apps/deck/lib/Service/BoardService.php on line 177 and defined in /usr/share/webapps/nextcloud/lib/private/Group/Manager.php:325
Stack trace:
#0 /var/lib/nextcloud/apps/deck/lib/Service/BoardService.php(177): OC\Group\Manager->getUserGroupIds(NULL)
#1 /var/lib/nextcloud/apps/deck/lib/Service/BoardService.php(105): OCA\Deck\Service\BoardService->getBoardPrerequisites()
#2 /var/lib/nextcloud/apps/deck/lib/Command/UserExport.php(96): OCA\Deck\Service\BoardService->findAll(Array)
#3 /usr/share/webapps/nextcloud/3rdparty/symfony/console/Command/Command.php(255): OCA\Deck\Command\UserExport->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#4 /usr/share/webapps/nextcloud/3rdparty/symfony/console/Application.php(901): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#5 /usr/share/webapps/nextcloud/3rdparty/symfony/console/Application.php(262): Symfony\Component\Console\Application->doRunCommand(Object(OCA\Deck\Command\UserExport), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#6 /usr/share/webapps/nextcloud/3rdparty/symfony/console/Application.php(145): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#7 /usr/share/webapps/nextcloud/lib/private/Console/Application.php(213): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#8 /usr/share/webapps/nextcloud/console.php(97): OC\Console\Application->run()
#9 /usr/share/webapps/nextcloud/occ(11): require_once('/usr/share/weba...')
```

**Version Details:**
 - OS: Alpine Linux 3.10.2
 - DB Version: PostgreSQL 11
 - PHP Version: 7.3.10
 - Browser: N/A
 - Nextcloud Version: 16.05
 - App Version: 0.6.6
 - Device: N/A

**Comment by DBJRdev** [comment]
Same problem here. 

Nextcloud 17.0.1
Deck 0.7.0
User IDs constructed as firstname.givenname
```
php occ deck:export john.doe

An unhandled exception has been thrown:
TypeError: Argument 1 passed to OC\Group\Manager::getUserGroupIds() must implement interface OCP\IUser, null given, called in /usr/www/users/ {{ OBSCURED FOR PRIVACY }} /apps/deck/lib/Service/BoardService.php on line 177 and defined in /usr/www/users/ {{ OBSCURED FOR PRIVACY }} /lib/private/Group/Manager.php:325
Stack trace:
#0 /usr/www/users/ {{ OBSCURED FOR PRIVACY }} /apps/deck/lib/Service/BoardService.php(177): OC\Group\Manager->getUserGroupIds(NULL)
#1 /usr/www/users/ {{ OBSCURED FOR PRIVACY }} /apps/deck/lib/Service/BoardService.php(105): OCA\Deck\Service\BoardService->getBoardPrerequisites()
#2 /usr/www/users/ {{ OBSCURED FOR PRIVACY }} /apps/deck/lib/Command/UserExport.php(96): OCA\Deck\Service\BoardService->findAll(Array)
#3 /usr/www/users/ {{ OBSCURED FOR PRIVACY }} /3rdparty/symfony/console/Command/Command.php(255): OCA\Deck\Command\UserExport->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#4 /usr/www/users/ {{ OBSCURED FOR PRIVACY }} /3rdparty/symfony/console/Application.php(908): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#5 /usr/www/users/ {{ OBSCURED FOR PRIVACY }} /3rdparty/symfony/console/Application.php(269): Symfony\Component\Console\Application->doRunCommand(Object(OCA\Deck\Command\UserExport), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#6 /usr/www/users/ {{ OBSCURED FOR PRIVACY }} /3rdparty/symfony/console/Application.php(145): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#7 /usr/www/users/ {{ OBSCURED FOR PRIVACY }} /lib/private/Console/Application.php(213): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#8 /usr/www/users/ {{ OBSCURED FOR PRIVACY }} /console.php(97): OC\Console\Application->run()
#9 /usr/www/users/ {{ OBSCURED FOR PRIVACY }} /occ(11): require_once('/usr/www/users/...')
```
