### ISSUE TITLE
Nightly builds are not uploaded properly

### ISSUE THREAD

**Issue by juliushaertl** [nextcloud/deck#1595]
```
020-03-11T01:02:03.7704035Z App cloned to "/tmp/krankerl.zdJybT9GofQE"
2020-03-11T01:02:03.7704656Z Dependency installation skipped
2020-03-11T01:02:03.7705288Z Building app
2020-03-11T01:02:03.7705524Z Executing packaging commands...
2020-03-11T01:02:03.7705724Z Running `make release`...
2020-03-11T01:03:37.2883340Z Executed all packaging commands.
2020-03-11T01:03:37.2883889Z App built
2020-03-11T01:03:37.2884514Z Writing compressed app archive to "./build/artifacts/deck.tar.gz"...
2020-03-11T01:03:38.0056638Z Packaged app as "./build/artifacts/deck.tar.gz"
2020-03-11T01:05:18.9070923Z ##[group]Run git config --local user.email "action@github.com"
2020-03-11T01:05:18.9071178Z [36;1mgit config --local user.email "action@github.com"[0m
2020-03-11T01:05:18.9071308Z [36;1mgit config --local user.name "GitHub Action"[0m
2020-03-11T01:05:18.9071427Z [36;1mgit tag -f nightly[0m
2020-03-11T01:05:18.9105927Z shell: /bin/bash -e {0}
2020-03-11T01:05:18.9106045Z ##[endgroup]
2020-03-11T01:05:18.9220059Z Updated tag 'nightly' (was 26d895df)
2020-03-11T01:05:18.9343981Z ##[group]Run juliushaertl/github-push-action@master
2020-03-11T01:05:18.9344124Z with:
2020-03-11T01:05:18.9344911Z   github_token: ***
2020-03-11T01:05:18.9345036Z   tags: true
2020-03-11T01:05:18.9345153Z   force: true
2020-03-11T01:05:18.9345254Z   branch: master
2020-03-11T01:05:18.9345369Z   directory: .
2020-03-11T01:05:18.9345487Z ##[endgroup]
2020-03-11T01:05:18.9704130Z Started: bash /home/runner/work/_actions/juliushaertl/github-push-action/master/start.sh
2020-03-11T01:05:18.9750784Z Push to branch master
2020-03-11T01:05:21.5097157Z To https://github.com/nextcloud/deck.git
2020-03-11T01:05:21.5099643Z  + 26d895df...ebafe3c9 nightly -> nightly (forced update)
2020-03-11T01:05:21.5425342Z ##[group]Run juliushaertl/action-release@master
2020-03-11T01:05:21.5425481Z with:
2020-03-11T01:05:21.5426215Z   token: ***
2020-03-11T01:05:21.5426331Z   tag: nightly
2020-03-11T01:05:21.5426439Z   files: ./build/artifacts/deck.tar.gz
2020-03-11T01:05:21.5426555Z   name: Nightly build
2020-03-11T01:05:21.5426667Z   body: Nightly release of deck

2020-03-11T01:05:21.5426780Z   draft: false
2020-03-11T01:05:21.5426886Z   prerelease: true
2020-03-11T01:05:21.5426980Z   overwrite: true
2020-03-11T01:05:21.5427087Z ##[endgroup]
2020-03-11T01:05:42.8176736Z ðŸŽ„ <- That is when I wrote this code.
2020-03-11T01:05:43.4279604Z Deprecation: [@octokit/rest] "file" parameter is deprecated for ".repos.uploadReleaseAsset()". Use "data" instead
2020-03-11T01:05:43.4281112Z Found The ðŸ¦ž. Updating GitHub release for tag "nightly".
2020-03-11T01:05:43.4283028Z     at /home/runner/work/_actions/juliushaertl/action-release/master/node_modules/@octokit/plugin-rest-endpoint-methods/dist-node/index.js:13145:26
2020-03-11T01:05:43.4283586Z ðŸš§ Uploading deck.tar.gz.
2020-03-11T01:05:43.4284217Z     at Array.forEach (<anonymous>)
2020-03-11T01:05:43.4285131Z     at Object.patchedMethod [as uploadReleaseAsset] (/home/runner/work/_actions/juliushaertl/action-release/master/node_modules/@octokit/plugin-rest-endpoint-methods/dist-node/index.js:13142:26)
2020-03-11T01:05:43.4286222Z     at upload (/home/runner/work/_actions/juliushaertl/action-release/master/action.js:168:48)
2020-03-11T01:05:43.4286696Z     at /home/runner/work/_actions/juliushaertl/action-release/master/action.js:189:15
2020-03-11T01:05:43.4286972Z     at processTicksAndRejections (internal/process/task_queues.js:93:5) {
2020-03-11T01:05:43.4287270Z   name: 'Deprecation'
2020-03-11T01:05:43.4287515Z }
2020-03-11T01:05:43.7950485Z âš ï¸ Failed to upload file RequestError [HttpError]: Validation Failed: {"resource":"ReleaseAsset","code":"already_exists","field":"name"}
2020-03-11T01:05:43.7951439Z All is norminal ðŸš€. Execution has ended.
2020-03-11T01:05:43.7953407Z     at /home/runner/work/_actions/juliushaertl/action-release/master/node_modules/@octokit/request/dist-node/index.js:66:23
2020-03-11T01:05:43.7954090Z     at processTicksAndRejections (internal/process/task_queues.js:93:5)
2020-03-11T01:05:43.7955124Z     at async upload (/home/runner/work/_actions/juliushaertl/action-release/master/action.js:168:32)
2020-03-11T01:05:43.7956146Z     at async /home/runner/work/_actions/juliushaertl/action-release/master/action.js:189:9 {
2020-03-11T01:05:43.7956913Z   name: 'HttpError',
2020-03-11T01:05:43.7957394Z   status: 422,
2020-03-11T01:05:43.7957887Z   headers: {
2020-03-11T01:05:43.7958628Z     'cache-control': 'no-cache',
2020-03-11T01:05:43.7960081Z     connection: 'close',
2020-03-11T01:05:43.7960887Z     'content-length': '207',
2020-03-11T01:05:43.7962904Z     'content-security-policy': "default-src 'none'",
2020-03-11T01:05:43.7963787Z     'content-type': 'application/json; charset=utf-8',
2020-03-11T01:05:43.7964644Z     date: 'Wed, 11 Mar 2020 01:05:43 GMT',
2020-03-11T01:05:43.7965494Z     'strict-transport-security': 'max-age=31557600',
2020-03-11T01:05:43.7966347Z     vary: 'Accept-Encoding, Accept, X-Requested-With',
2020-03-11T01:05:43.7967156Z     'x-content-type-options': 'nosniff',
2020-03-11T01:05:43.7967920Z     'x-frame-options': 'deny',
2020-03-11T01:05:43.7968761Z     'x-github-media-type': 'github.v3; format=json',
2020-03-11T01:05:43.7969664Z     'x-github-request-id': '0400:7319:B3B3:D846:5E683967',
2020-03-11T01:05:43.7970448Z     'x-xss-protection': '1; mode=block'
2020-03-11T01:05:43.7970914Z   },
2020-03-11T01:05:43.7971454Z   request: {
2020-03-11T01:05:43.7972154Z     method: 'POST',
2020-03-11T01:05:43.7973280Z     url: 'https://uploads.github.com/repos/nextcloud/deck/releases/23178995/assets?name=deck.tar.gz&',
2020-03-11T01:05:43.7973850Z     headers: {
2020-03-11T01:05:43.7974659Z       accept: 'application/vnd.github.v3+json',
2020-03-11T01:05:43.7975889Z       'user-agent': 'octokit.js/16.43.1 Node.js/12.13.1 (Linux 5.0; x64)',
2020-03-11T01:05:43.7976805Z       'content-type': 'application/gzip',
2020-03-11T01:05:43.7984845Z       'content-length': 3158032,
2020-03-11T01:05:43.7985659Z       authorization: 'token [REDACTED]'
2020-03-11T01:05:43.7985919Z     },
2020-03-11T01:05:43.7986484Z     body: <Buffer 1f 8b 08 00 00 00 00 00 00 ff ec bd 09 60 5c 57 79 28 2c 27 61 c9 b0 75 05 5e 81 72 a3 04 6c 81 66 34 33 5a 2d 2f b1 2c cb b1 88 6d a9 96 9c 90 26 79 ... 3157982 more bytes>,
2020-03-11T01:05:43.7986919Z     request: { hook: [Function: bound bound register], validate: [Object] }
2020-03-11T01:05:43.7987187Z   },
2020-03-11T01:05:43.7987782Z   request_id: '0400:7319:B3B3:D846:5E683967',
2020-03-11T01:05:43.7988444Z   documentation_url: 'https://developer.github.com/v3',
2020-03-11T01:05:43.7988778Z   errors: [
2020-03-11T01:05:43.7989441Z     { resource: 'ReleaseAsset', code: 'already_exists', field: 'name' }
2020-03-11T01:05:43.7989707Z   ]
2020-03-11T01:05:43.7990145Z }
2020-03-11T01:05:43.8041098Z Cleaning up orphan processes
```

**Comment by juliushaertl** [comment]
Seems there was a broken asset present for some reason, fixed.
