### ISSUE TITLE
Logging into deck android app throws error 

### ISSUE THREAD

**Issue by dennorske** [nextcloud/deck#2082]
Hello,

Using nextcloud client on my android 10 phone, and I have used deck previously. Installed it from f-droid. 

Log when trying to log in to my already existing account on my device:

```
App Version: 1.5.0
App Version Code: 1005000
App Flavor: fdroid

Deck Server Version: 0.6.4

Files App Version Code: com.nextcloud.client

---

OS Version: 4.14.117-perf+(2005132200)
OS API Level: 29
Device: OnePlus7Pro
Manufacturer: OnePlus
Model (and Product): GM1913 (OnePlus7Pro_EEA)

---

java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Long it.niedermann.nextcloud.deck.model.Card.getStackId()' on a null object reference
	at it.niedermann.nextcloud.deck.persistence.sync.helpers.providers.CardDataProvider.goDeeperForUpSync(CardDataProvider.java:193)
	at it.niedermann.nextcloud.deck.persistence.sync.helpers.providers.StackDataProvider.goDeeperForUpSync(StackDataProvider.java:120)
	at it.niedermann.nextcloud.deck.persistence.sync.helpers.providers.BoardDataProvider.goDeeperForUpSync(BoardDataProvider.java:126)
	at it.niedermann.nextcloud.deck.persistence.sync.helpers.SyncHelper.doUpSyncFor(SyncHelper.java:100)
	at it.niedermann.nextcloud.deck.persistence.sync.helpers.SyncHelper.doUpSyncFor(SyncHelper.java:80)
	at it.niedermann.nextcloud.deck.persistence.sync.SyncManager$3$1.lambda$onResponse$0(SyncManager.java:189)
	at it.niedermann.nextcloud.deck.persistence.sync.-$$Lambda$SyncManager$3$1$3iKicNZlgWASgTHun34YoNfq7LQ.run(Unknown Source:4)
	at java.lang.Thread.run(Thread.java:919)

```

Anything that can be fixed, or something I can try?

**Comment by stefan-niedermann** [comment]
Hey @dennorske 

please follow these steps: https://github.com/stefan-niedermann/nextcloud-deck/wiki/FAQ - if not successsful, open the issue in the repository for the Android app (linked in the FAQ) and fill in the complete issue template.

This repository is only for the server app.

Regards
