### ISSUE TITLE
Can't save note from Android app

### ISSUE THREAD

**Issue by xplosionmind** [nextcloud/deck#2089]
After clicking on the "V" to save a note in a list, I grt this error message. It includes also data about my device and the version of the app.

```
App Version: 1.5.4
App Version Code: 1005004
App Flavor: fdroid

Files App Version Code: 30120090

---

OS Version: 4.9.179-perf+(2002220019)
OS API Level: 29
Device: OnePlus6T
Manufacturer: OnePlus
Model (and Product): ONEPLUS A6013 (OnePlus6T)

---

java.lang.NullPointerException: Attempt to invoke virtual method 'long java.lang.Long.longValue()' on a null object reference
	at it.niedermann.nextcloud.deck.persistence.sync.helpers.providers.CardPropagationDataProvider.createOnServer(CardPropagationDataProvider.java:22)
	at it.niedermann.nextcloud.deck.persistence.sync.helpers.providers.CardPropagationDataProvider.createOnServer(CardPropagationDataProvider.java:12)
	at it.niedermann.nextcloud.deck.persistence.sync.helpers.SyncHelper.doUpSyncFor(SyncHelper.java:96)
	at it.niedermann.nextcloud.deck.persistence.sync.helpers.SyncHelper.doUpSyncFor(SyncHelper.java:80)
	at it.niedermann.nextcloud.deck.persistence.sync.SyncManager.lambda$updateCard$27$SyncManager(SyncManager.java:904)
	at it.niedermann.nextcloud.deck.persistence.sync.-$$Lambda$SyncManager$e3CkeNUm6klHgpxESZl2i8zpJuM.run(Unknown Source:6)
	at java.lang.Thread.run(Thread.java:919)

```

**Comment by stefan-niedermann** [comment]
Dear @xplosionmind 

this repository is for the server app only.

For the android app please follow those steps: https://github.com/stefan-niedermann/nextcloud-deck/wiki/FAQ#frequently-asked-questions

Regards
