### ISSUE TITLE
Android Deck app connection failing

### ISSUE THREAD

**Issue by HelplessFool** [nextcloud/deck#2202]
Nextcloud is running on ubuntu server, with Deck installed and working.  Can access it from another Android device.

The device I got this error from previously could access Deck, I then deleted the account from within the app as it didn't appear to be working and now it will not connect again.  Another device gives a slightly different error and has never been able to connect.

Error message as provided by the first app:

```
App Version: 1.9.7
App Version Code: 1009007
App Flavor: fdroid

Deck Server Version: 0.6.4

Files App Version Code: 30120190

---

OS Version: 3.10.49-cyanogen-ge4cc700(c295bd1167)
OS API Level: 22
Device: crackling
Manufacturer: Wileyfox
Model (and Product): Wileyfox Swift (Swift)

---

it.niedermann.nextcloud.deck.exceptions.DeckException: deck node is missing in capabilities endpoint!
	at it.niedermann.nextcloud.deck.api.JsonToEntityParser.parseCapabilities(JsonToEntityParser.java:541)
	at it.niedermann.nextcloud.deck.api.JsonToEntityParser.parseJsonObject(JsonToEntityParser.java:58)
	at it.niedermann.nextcloud.deck.api.NextcloudDeserializer.deserialize(NextcloudDeserializer.java:30)
	at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69)
	at com.google.gson.Gson.fromJson(Gson.java:932)
	at com.google.gson.Gson.fromJson(Gson.java:897)
	at com.nextcloud.android.sso.api.NextcloudAPI.convertStreamToTargetEntity(NextcloudAPI.java:135)
	at com.nextcloud.android.sso.api.NextcloudAPI.lambda$performRequestObservableV2$1$NextcloudAPI(NextcloudAPI.java:111)
	at com.nextcloud.android.sso.api.-$$Lambda$NextcloudAPI$HPzOdi9LOc_f-wA9GNnhc9LKQSM.subscribe(lambda)
	at io.reactivex.internal.operators.observable.ObservableFromPublisher.subscribeActual(ObservableFromPublisher.java:31)
	at io.reactivex.Observable.subscribe(Observable.java:12284)
	at io.reactivex.internal.operators.observable.ObservableSubscribeOn$SubscribeTask.run(ObservableSubscribeOn.java:96)
	at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:578)
	at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
	at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:152)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:265)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
	at java.lang.Thread.run(Thread.java:818)

```

Any suggestions on how to debug this, or find out what's going wrong?  The device can still connect to the server using the Nextcloud app.

**Comment by juliushaertl** [comment]
cc @stefan-niedermann 

However I'd suggest to open an issue in the android app repo https://github.com/stefan-niedermann/nextcloud-deck
