### ISSUE TITLE
Crash after Update to 1.16.2

### ISSUE THREAD

**Issue by mstaegemann** [nextcloud/deck#2971]
**Describe the bug**
After Update Desk to 1.16.2 from F-Droid I got the following exception
```
App Version: 1.16.2
App Version Code: 1016002
Server App Version: 0.6.4
App Flavor: fdroid

Files App Version Code: 30150190

---

OS Version: 4.14.113-21324211(G975FXXU9FUCD)
OS API Level: 30
Device: beyond2
Manufacturer: samsung
Model (and Product): SM-G975F (beyond2lteeea)

---
c.b.a.a.e.n: c.b.a.a.c.c
	at c.b.a.a.d.i.j(Unknown Source:33)
	at c.b.a.a.d.k.h(Unknown Source:6)
	at c.b.a.a.d.k.e(Unknown Source:0)
	at c.b.a.a.d.k.f(Unknown Source:0)
	at c.b.a.a.d.e.a(Unknown Source:6)
	at e.b.i.e.b.c.g(Unknown Source:7)
	at e.b.b.a(Unknown Source:14)
	at e.b.i.e.b.e$b.run(Unknown Source:6)
	at e.b.e$a.run(Unknown Source:9)
	at e.b.i.f.h.run(Unknown Source:13)
	at e.b.i.f.h.call(Unknown Source:0)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:923)
```

**To Reproduce**
Install App from F-Droid and it happened just

**Client details:**
 - Device: Samsung S10+ with latest patch

**Other details
 - Nextcloud work with a self-signed certificate
 - Android Nextcloud Client, Nextcloud Notes work fine.
 - Try to uninstall Desk, clean cache and data. --> Same issue

**Comment by stefan-niedermann** [comment]
Wrong repository buddy 😉 
https://github.com/stefan-niedermann/nextcloud-deck/issues/930#issuecomment-818025817
