### ISSUE TITLE
App crash after login

### ISSUE THREAD

**Issue by OfficialMuffin** [nextcloud/deck#2976]
```
App Version: 1.16.2
App Version Code: 1016002
Server App Version: 0.6.4
App Flavor: fdroid

Files App Version Code: 30150190

---

OS Version: 4.19.113-21033099(T870XXU2BUC6)
OS API Level: 30
Device: gts7lwifi
Manufacturer: samsung
Model (and Product): SM-T870 (gts7lwifieea)

---

c.b.a.a.e.n: c.b.a.a.c.c
	at c.b.a.a.d.i.j(Unknown Source:33)
	at c.b.a.a.d.k.h(Unknown Source:6)
	at c.b.a.a.d.k.e(Unknown Source:0)
	at c.b.a.a.d.k.f(Unknown Source:0)
	at c.b.a.a.d.e.a(Unknown Source:6)
	at e.b.i.e.b.c.g(Unknown Source:7)
	at e.b.b.a(Unknown Source:14)
	at e.b.i.e.b.e$b.run(Unknown Source:6)
	at e.b.e$a.run(Unknown Source:9)
	at e.b.i.f.h.run(Unknown Source:13)
	at e.b.i.f.h.call(Unknown Source:0)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:923)

`

**Comment by stefan-niedermann** [comment]
Wrong repository buddy 😉 
https://github.com/stefan-niedermann/nextcloud-deck/issues/930#issuecomment-818025817

**Comment by OfficialMuffin** [comment]
Thanks, will have to downgrade then
