### ISSUE TITLE
cannot login to hetzner.de storageshare

### ISSUE THREAD

**Issue by pointout** [nextcloud/deck#2980]
I have a hetzner.de storage share, which is a managed nextcloud. When I try to login this is shown:

```
App Version: 1.16.2
App Version Code: 1016002
Server App Version: 0.6.4
App Flavor: fdroid

Files App Version Code: 30150190

---

OS Version: 3.4.0-perf-g7c668d5(gms-24df0be9)
OS API Level: 25
Device: FP2
Manufacturer: Fairphone
Model (and Product): FP2 (FP2)

---

c.b.a.a.e.n: c.b.a.a.c.c
	at c.b.a.a.d.i.j()
	at c.b.a.a.d.k.h()
	at c.b.a.a.d.k.e()
	at c.b.a.a.d.k.f()
	at c.b.a.a.d.e.a()
	at e.b.i.e.b.c.g()
	at e.b.b.a()
	at e.b.i.e.b.e$b.run()
	at e.b.e$a.run()
	at e.b.i.f.h.run()
	at e.b.i.f.h.call()
	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:272)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
	at java.lang.Thread.run(Thread.java:761)

```

and under the login-button some letters with points are shown. Like in the first line of debug message.

**Comment by stefan-niedermann** [comment]
Wrong repository buddy 😉 
https://github.com/stefan-niedermann/nextcloud-deck/issues/930#issuecomment-818025817
