### ISSUE TITLE
Due date is not saving because of invalid datetime format

### ISSUE THREAD

**Issue by Glosshead** [nextcloud/deck#326]
### Steps to reproduce
1. Select card and fill up due date
2. Leave the card
3. Refresh screen or click on the same card

### Expected behaviour
Due date saving normally

### Actual behaviour
Due date is empty on screen refresh or even card leave/enter

### General server configuration

**Operating system:** Linux cloud.he$$$$p.ru 3.10.0-693.2.2.el7.x86_64 #1 SMP Tue Sep 12 22:26:13 UTC 2017 x86_64

**Web server:** nginx/1.13.5 (fpm-fcgi)
> nginx -V
> nginx version: nginx/1.13.5
> built by gcc 4.8.5 20150623 (Red Hat 4.8.5-11) (GCC) 
> built with OpenSSL 1.0.1e-fips 11 Feb 2013
> TLS SNI support enabled
> configure arguments: --prefix=/etc/nginx --sbin-path=/usr/sbin/nginx --modules-path=/usr/lib64/nginx/modules --conf-path=/etc/nginx/nginx.conf --error-log-path=/var/log/nginx/error.log --http-log-path=/var/log/nginx/access.log --pid-path=/var/run/nginx.pid --lock-path=/var/run/nginx.lock --http-client-body-temp-path=/var/cache/nginx/client_temp --http-proxy-temp-path=/var/cache/nginx/proxy_temp --http-fastcgi-temp-path=/var/cache/nginx/fastcgi_temp --http-uwsgi-temp-path=/var/cache/nginx/uwsgi_temp --http-scgi-temp-path=/var/cache/nginx/scgi_temp --user=nginx --group=nginx --with-compat --with-file-aio --with-threads --with-http_addition_module --with-http_auth_request_module --with-http_dav_module --with-http_flv_module --with-http_gunzip_module --with-http_gzip_static_module --with-http_mp4_module --with-http_random_index_module --with-http_realip_module --with-http_secure_link_module --with-http_slice_module --with-http_ssl_module --with-http_stub_status_module --with-http_sub_module --with-http_v2_module --with-mail --with-mail_ssl_module --with-stream --with-stream_realip_module --with-stream_ssl_module --with-stream_ssl_preread_module --with-cc-opt='-O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -fPIC' --with-ld-opt='-Wl,-z,relro -Wl,-z,now -pie'

**Database:** 
> mysql  Ver 15.1 Distrib 10.2.9-MariaDB, for Linux (x86_64) using readline 5.1

**PHP version:** 
>PHP 7.1.10 (cli) (built: Sep 27 2017 08:27:18) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.1.10, Copyright (c) 1999-2017, by Zend Technologies

<details>
        <summary>PHP-modules loaded</summary>

```
 - Core
 - date
 - libxml
 - openssl
 - pcre
 - zlib
 - filter
 - hash
 - Reflection
 - SPL
 - session
 - standard
 - cgi-fcgi
 - bcmath
 - bz2
 - calendar
 - ctype
 - curl
 - dba
 - dom
 - mbstring
 - fileinfo
 - ftp
 - gd
 - gettext
 - gmp
 - iconv
 - imap
 - intl
 - json
 - ldap
 - exif
 - mcrypt
 - mysqlnd
 - PDO
 - apcu
 - posix
 - shmop
 - SimpleXML
 - soap
 - sockets
 - sqlite3
 - sysvmsg
 - sysvsem
 - sysvshm
 - tokenizer
 - xml
 - xmlwriter
 - xsl
 - mysqli
 - pdo_mysql
 - pdo_sqlite
 - wddx
 - xmlreader
 - apc
 - imagick
 - zip
 - Phar
 - Zend OPcache
```
</details>

### Nextcloud configuration

**Nextcloud version:** 12.0.3 - 12.0.3.3

**Updated from an older Nextcloud/ownCloud or fresh install:** Fresh installation

**Where did you install Nextcloud from:**
> https://download.nextcloud.com/server/releases/nextcloud-12.0.3.tar.bz2

**Are you using external storage, if yes which one:** files_external is disabled

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:**
> (LDAP/ActiveDirectory/Webdav/...)

<details>
        <summary>Signing status</summary>

```
[]
```
</details>

<details>
        <summary>Enabled apps</summary>

```
 - activity: 2.5.2
 - bruteforcesettings: 1.0.2
 - calendar: 1.5.5
 - comments: 1.2.0
 - contacts: 2.0.1
 - dashboard: 4.0.5
 - dav: 1.3.0
 - deck: 0.2.4
 - federatedfilesharing: 1.2.0
 - federation: 1.2.0
 - files: 1.7.2
 - files_automatedtagging: 1.2.2
 - files_downloadactivity: 1.1.1
 - files_pdfviewer: 1.1.1
 - files_sharing: 1.4.0
 - files_texteditor: 2.4.1
 - files_trashbin: 1.2.0
 - files_versions: 1.5.0
 - files_videoplayer: 1.1.0
 - firstrunwizard: 2.1
 - gallery: 17.0.0
 - issuetemplate: 0.2.2
 - logreader: 2.0.0
 - lookup_server_connector: 1.0.0
 - nextcloud_announcements: 1.1
 - notifications: 2.0.0
 - oauth2: 1.0.5
 - password_policy: 1.2.2
 - previewgenerator: 1.0.7
 - provisioning_api: 1.2.0
 - richdocuments: 1.12.35
 - serverinfo: 1.2.0
 - sharebymail: 1.2.0
 - socialsharing_email: 1.0.1
 - survey_client: 1.0.0
 - systemtags: 1.2.0
 - tasks: 0.9.5
 - theming: 1.3.0
 - theming_customcss: 1.0.0
 - twofactor_backupcodes: 1.1.1
 - updatenotification: 1.2.0
 - user_ldap: 1.2.1
 - workflowengine: 1.2.0
```
</details>

<details>
        <summary>Disabled apps</summary>

```
 - admin_audit
 - encryption
 - files_external
 - user_external
```
</details>

<details>
        <summary>Content of config/config.php</summary>

```
{
    "instanceid": "oc61k7ylewls",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "10.110.0.215",
        "files.herocamp.ru",
        "cloud.herocamp.ru",
        "195.9.210.142"
    ],
    "debug": true,
    "datadirectory": "\/var\/www\/data",
    "overwrite.cli.url": "http:\/\/10.110.0.215",
    "dbtype": "mysql",
    "version": "12.0.3.3",
    "dbname": "cloud",
    "dbhost": "db01.herocamp.ru",
    "dbport": "3306",
    "dbtableprefix": "oc_",
    "mysql.utf8mb4": true,
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "installed": true,
    "memcache.local": "\\OC\\Memcache\\APCu",
    "mail_from_address": "cloud",
    "mail_smtpmode": "php",
    "mail_smtpauthtype": "LOGIN",
    "mail_domain": "herocamp.ru",
    "ldapIgnoreNamingRules": false,
    "ldapProviderFactory": "\\OCA\\User_LDAP\\LDAPProviderFactory",
    "updater.release.channel": "stable"
}
```
</details>

<details>
        <summary>LDAP config</summary>

```
[$$$$@cloud www]# sudo -u $$$$ php occ ldap:show-config
+-------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Configuration                 |                                                                                                                                                                                    |
+-------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| hasMemberOfFilterSupport      | 1                                                                                                                                                                                  |
| hasPagedResultSupport         |                                                                                                                                                                                    |
| homeFolderNamingRule          | attr:cn                                                                                                                                                                            |
| lastJpegPhotoLookup           | 0                                                                                                                                                                                  |
| ldapAgentName                 | CN=name,CN=Users,DC=h$$$$$$p,DC=ru                                                                                                                                          |
| ldapAgentPassword             | ***                                                                                                                                                                                |
| ldapAttributesForGroupSearch  |                                                                                                                                                                                    |
| ldapAttributesForUserSearch   |                                                                                                                                                                                    |
| ldapBackupHost                |                                                                                                                                                                                    |
| ldapBackupPort                |                                                                                                                                                                                    |
| ldapBase                      | DC=h$$$$$p,DC=ru                                                                                                                                                                  |
| ldapBaseGroups                | DC=h$$$$$p,DC=ru                                                                                                                                                                  |
| ldapBaseUsers                 | DC=h$$$$$$p,DC=ru                                                                                                                                                                  |
| ldapCacheTTL                  | 600                                                                                                                                                                                |
| ldapConfigurationActive       | 1                                                                                                                                                                                  |
| ldapDefaultPPolicyDN          |                                                                                                                                                                                    |
| ldapDynamicGroupMemberURL     |                                                                                                                                                                                    |
| ldapEmailAttribute            | mail                                                                                                                                                                               |
| ldapExperiencedAdmin          | 0                                                                                                                                                                                  |
| ldapExpertUUIDGroupAttr       |                                                                                                                                                                                    |
| ldapExpertUUIDUserAttr        |                                                                                                                                                                                    |
| ldapExpertUsernameAttr        |                                                                                                                                                                                    |
| ldapGidNumber                 | gidNumber                                                                                                                                                                          |
| ldapGroupDisplayName          | cn                                                                                                                                                                                 |
| ldapGroupFilter               | (|(cn=Domain users))                                                                                                                                                        |
| ldapGroupFilterGroups         | Domain users                                                                                                                                                                |
| ldapGroupFilterMode           | 0                                                                                                                                                                                  |
| ldapGroupFilterObjectclass    |                                                                                                                                                                                    |
| ldapGroupMemberAssocAttr      | uniqueMember                                                                                                                                                                       |
| ldapHost                      | dc01.h$$$$$$p.ru                                                                                                                                                                   |
| ldapIgnoreNamingRules         |                                                                                                                                                                                    |
| ldapLoginFilter               | (&(&(|(objectclass=person))(|(|(memberof=CN=Domain users,CN=Users,DC=h$$$$$$p,DC=ru)(primaryGroupID=513))))(|(samaccountname=%uid)(|(mailPrimaryAddress=%uid)(mail=%uid)))) |
| ldapLoginFilterAttributes     |                                                                                                                                                                                    |
| ldapLoginFilterEmail          | 1                                                                                                                                                                                  |
| ldapLoginFilterMode           | 0                                                                                                                                                                                  |
| ldapLoginFilterUsername       | 1                                                                                                                                                                                  |
| ldapNestedGroups              | 0                                                                                                                                                                                  |
| ldapOverrideMainServer        |                                                                                                                                                                                    |
| ldapPagingSize                | 500                                                                                                                                                                                |
| ldapPort                      | 389                                                                                                                                                                                |
| ldapQuotaAttribute            |                                                                                                                                                                                    |
| ldapQuotaDefault              |                                                                                                                                                                                    |
| ldapTLS                       | 0                                                                                                                                                                                  |
| ldapUserDisplayName           | displayName                                                                                                                                                                        |
| ldapUserDisplayName2          |                                                                                                                                                                                    |
| ldapUserFilter                | (&(|(objectclass=person))(|(|(memberof=CN=Domain users,CN=Users,DC=h$$$$$$p,DC=ru)(primaryGroupID=513))))                                                                   |
| ldapUserFilterGroups          | Domain users                                                                                                                                                                |
| ldapUserFilterMode            | 1                                                                                                                                                                                  |
| ldapUserFilterObjectclass     | person                                                                                                                                                                             |
| ldapUuidGroupAttribute        | auto                                                                                                                                                                               |
| ldapUuidUserAttribute         | auto                                                                                                                                                                               |
| turnOffCertCheck              | 0                                                                                                                                                                                  |
| turnOnPasswordChange          | 0                                                                                                                                                                                  |
| useMemberOfToDetectMembership | 1                                                                                                                                                                                  |
+-------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
```
</details>

### Client configuration

**Browser:** 
> Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.113 YaBrowser/17.9.1.888 Yowser/2.5 Safari/537.36
> Safari (Macintosh; Intel Mac OS X 10_12_6) Version 11.0 (12604.1.38.1.7)
> Chrome (Windows) Version 61.0.3163.100 (Official build), (64 bit)

**Operating system:** 
> macOS 10.12.6
> Windows 10 Pro 1703

### Logs

<details>
        <summary>Web server error log</summary>

```
10.110.0.15 - - [12/Oct/2017:12:03:11 +0300] "GET /apps/files/ HTTP/1.1" 200 7344 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.113 YaBrowser/17.9.1.888 Yowser/2.5 Safari/537.36" "-"
10.110.0.15 - - [12/Oct/2017:12:03:11 +0300] "GET /apps/deck/stacks/3 HTTP/1.1" 200 1879 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.113 YaBrowser/17.9.1.888 Yowser/2.5 Safari/537.36" "-"
10.110.0.15 - - [12/Oct/2017:12:03:11 +0300] "GET /apps/deck/boards/3 HTTP/1.1" 200 519 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.113 YaBrowser/17.9.1.888 Yowser/2.5 Safari/537.36" "-"
10.110.0.15 - - [12/Oct/2017:12:03:11 +0300] "GET /apps/files/ HTTP/1.1" 200 7333 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.113 YaBrowser/17.9.1.888 Yowser/2.5 Safari/537.36" "-"
10.110.0.15 - - [12/Oct/2017:12:03:11 +0300] "GET /cron.php HTTP/1.1" 200 51 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.113 YaBrowser/17.9.1.888 Yowser/2.5 Safari/537.36" "-"
10.110.0.15 - - [12/Oct/2017:12:03:11 +0300] "GET /core/vendor/select2/select2x2.png HTTP/1.1" 304 0 "https://cloud.herocamp.ru/core/vendor/select2/select2.css" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.113 YaBrowser/17.9.1.888 Yowser/2.5 Safari/537.36" "-"
10.110.0.15 - - [12/Oct/2017:12:03:11 +0300] "GET /apps/theming/img/core/filetypes/text.svg?v=10 HTTP/1.1" 304 0 "https://cloud.herocamp.ru/apps/theming/styles?v=10" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.113 YaBrowser/17.9.1.888 Yowser/2.5 Safari/537.36" "-"
10.110.0.15 - - [12/Oct/2017:12:03:22 +0300] "GET /core/css/images/ui-bg_flat_100_ffffff_40x100.png HTTP/1.1" 304 0 "https://cloud.h$$$$$p.ru/core/css/jquery-ui-fixes.css" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.113 YaBrowser/17.9.1.888 Yowser/2.5 Safari/537.36" "-"
10.110.0.15 - - [12/Oct/2017:12:03:22 +0300] "PUT /apps/deck/cards/7 HTTP/1.1" 500 17564 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.113 YaBrowser/17.9.1.888 Yowser/2.5 Safari/537.36" "-"
10.110.0.15 - - [12/Oct/2017:12:05:48 +0300] "POST /heartbeat HTTP/1.1" 200 31 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.113 YaBrowser/17.9.1.888 Yowser/2.5 Safari/537.36" "-"
```
</details>

<details>
        <summary>Nextcloud log (data/nextcloud.log)</summary>

```
{"reqId":"c6tRi7WUuy3Ol4SLPmcU","level":3,"time":"2017-10-11T08:08:36+00:00","remoteAddr":"10.110.0.27","user":"B6B52D6B-C60A-4B62-ABB7-630F3AC2F121","app":"index","method":"PUT","url":"\/apps\/deck\/cards\/25","message":"Exception: {\"Exception\":\"Doctrine\\\\DBAL\\\\Exception\\\\DriverException\",\"Message\":\"An exception occurred while executing 'UPDATE `oc_deck_cards` SET `duedate` = ?,`last_modified` = ? WHERE `id` = ?' with params [\\\"2017-11-06T07:09:48+00:00\\\", 1507709316, 25]:\\n\\nSQLSTATE[22007]: Invalid datetime format: 1292 Incorrect datetime value: '2017-11-06T07:09:48+00:00' for column 'duedate' at row 1\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/DBALException.php(128): Doctrine\\\\DBAL\\\\Driver\\\\AbstractMySQLDriver->convertException('An exception oc...', Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOException))\\n#1 \\\/var\\\/www\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Statement.php(177): Doctrine\\\\DBAL\\\\DBALException::driverExceptionDuringQuery(Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOMySql\\\\Driver), Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOException), 'UPDATE `oc_deck...', Array)\\n#2 \\\/var\\\/www\\\/lib\\\/public\\\/AppFramework\\\/Db\\\/Mapper.php(247): Doctrine\\\\DBAL\\\\Statement->execute()\\n#3 \\\/var\\\/www\\\/apps\\\/deck\\\/lib\\\/Db\\\/DeckMapper.php(40): OCP\\\\AppFramework\\\\Db\\\\Mapper->execute('UPDATE `*PREFIX...', Array, NULL, NULL)\\n#4 \\\/var\\\/www\\\/lib\\\/public\\\/AppFramework\\\/Db\\\/Mapper.php(187): OCA\\\\Deck\\\\Db\\\\DeckMapper->execute('UPDATE `*PREFIX...', Array)\\n#5 \\\/var\\\/www\\\/apps\\\/deck\\\/lib\\\/Db\\\/CardMapper.php(50): OCP\\\\AppFramework\\\\Db\\\\Mapper->update(Object(OCA\\\\Deck\\\\Db\\\\Card))\\n#6 \\\/var\\\/www\\\/apps\\\/deck\\\/lib\\\/Service\\\/CardService.php(92): OCA\\\\Deck\\\\Db\\\\CardMapper->update(Object(OCA\\\\Deck\\\\Db\\\\Card))\\n#7 \\\/var\\\/www\\\/apps\\\/deck\\\/lib\\\/Controller\\\/CardController.php(94): OCA\\\\Deck\\\\Service\\\\CardService->update(25, '\\\\xD0\\\\xA0\\\\xD0\\\\xB5\\\\xD0\\\\xB0\\\\xD0\\\\xBB\\\\xD0\\\\xB8\\\\xD0\\\\xB7\\\\xD0\\\\xB0\\\\xD1...', 6, 'plain', 999, NULL, 'B6B52D6B-C60A-4...', '2017-11-06T07:0...')\\n#8 [internal function]: OCA\\\\Deck\\\\Controller\\\\CardController->update(25, '\\\\xD0\\\\xA0\\\\xD0\\\\xB5\\\\xD0\\\\xB0\\\\xD0\\\\xBB\\\\xD0\\\\xB8\\\\xD0\\\\xB7\\\\xD0\\\\xB0\\\\xD1...', 6, 'plain', 999, NULL, '2017-11-06T07:0...')\\n#9 \\\/var\\\/www\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(160): call_user_func_array(Array, Array)\\n#10 \\\/var\\\/www\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(90): OC\\\\AppFramework\\\\Http\\\\Dispatcher->executeController(Object(OCA\\\\Deck\\\\Controller\\\\CardController), 'update')\\n#11 \\\/var\\\/www\\\/lib\\\/private\\\/AppFramework\\\/App.php(114): OC\\\\AppFramework\\\\Http\\\\Dispatcher->dispatch(Object(OCA\\\\Deck\\\\Controller\\\\CardController), 'update')\\n#12 \\\/var\\\/www\\\/lib\\\/private\\\/AppFramework\\\/Routing\\\/RouteActionHandler.php(47): OC\\\\AppFramework\\\\App::main('OCA\\\\\\\\Deck\\\\\\\\Contro...', 'update', Object(OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer), Array)\\n#13 [internal function]: OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler->__invoke(Array)\\n#14 \\\/var\\\/www\\\/lib\\\/private\\\/Route\\\/Router.php(299): call_user_func(Object(OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler), Array)\\n#15 \\\/var\\\/www\\\/lib\\\/base.php(1004): OC\\\\Route\\\\Router->match('\\\/apps\\\/deck\\\/card...')\\n#16 \\\/var\\\/www\\\/index.php(48): OC::handleRequest()\\n#17 {main}\",\"File\":\"\\\/var\\\/www\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Driver\\\/AbstractMySQLDriver.php\",\"Line\":116}","userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/61.0.3163.100 Safari\/537.36","version":"12.0.3.3"}
```
</details>

<details>
        <summary>Browser log</summary>

```
JS log
angular.min.js:108 PUT https://cloud.herocamp.ru/apps/deck/cards/7 500 (Internal Server Error)
(anonymous) @ angular.min.js:108
p @ angular.min.js:103
(anonymous) @ angular.min.js:101
(anonymous) @ angular.min.js:134
$digest @ angular.min.js:145
$apply @ angular.min.js:149
onSelect @ datepicker.js:35
_selectDate @ jquery-ui.custom.min.js:6
_selectDay @ jquery-ui.custom.min.js:6
selectDay @ jquery-ui.custom.min.js:6
dispatch @ jquery.min.js:3
r.handle @ jquery.min.js:3

angular.min.js:123 Possibly unhandled rejection: Updating cards failed
(anonymous) @ angular.min.js:123
(anonymous) @ angular.min.js:95
g @ angular.min.js:134
$digest @ angular.min.js:145
$apply @ angular.min.js:149
l @ angular.min.js:102
A.onload @ angular.min.js:107
XMLHttpRequest.send (async)
(anonymous) @ angular.min.js:108
p @ angular.min.js:103
(anonymous) @ angular.min.js:101
(anonymous) @ angular.min.js:134
$digest @ angular.min.js:145
$apply @ angular.min.js:149
onSelect @ datepicker.js:35
_selectDate @ jquery-ui.custom.min.js:6
_selectDay @ jquery-ui.custom.min.js:6
selectDay @ jquery-ui.custom.min.js:6
dispatch @ jquery.min.js:3
r.handle @ jquery.min.js:3

```
</details>

**Comment by Glosshead** [comment]
For me it was enough to change /apps/deck/lib/Db/Card.php at row 65 from 
> return $dt->format('c');
to 
> return $dt->format('Y-m-d H:i:s');

Sorry I'm not friendly with Git and don't know how to make this fix request by the right way.

**Comment by Glosshead** [comment]
Just seen it was fixed already.

Sorry for disturb.
