### ISSUE TITLE
Error when uploading image via Android App

### ISSUE THREAD

**Issue by henningaround** [nextcloud/deck#3377]
Hello,

does someone understand this error message and can help me to fix the problem?

```
App Version: 1.19.4
App Version Code: 1019004
Server App Version: 1.5.3
App Flavor: fdroid

Files App Version Code: 30170090OS Version: 4.14.113-22384011(M315FXXU2BUH8)
OS API Level: 30
Device: m31
Manufacturer: samsung
Model (and Product): SM-M315F (m31nseea)it.niedermann.nextcloud.deck.exceptions.UploadAttachmentFailedException: Unknown URI scheme
at it.niedermann.nextcloud.deck.ui.card.attachments.CardAttachmentsFragment$5.lambda$onError$1$CardAttachmentsFragment$5(CardAttachmentsFragment.java:484)
at it.niedermann.nextcloud.deck.ui.card.attachments.CardAttachmentsFragment$5$$ExternalSyntheticLambda1.run(Unknown Source:6)
at android.os.Handler.handleCallback(Handler.java:938)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:246)
at android.app.ActivityThread.main(ActivityThread.java:8595)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
Caused by: com.nextcloud.android.sso.exceptions.NextcloudHttpRequestFailedException: HTTP-Anfrage ist fehlgeschlagen mit HTTP-Statuscode: 500
at com.nextcloud.android.sso.api.AidlNetworkRequest.performNetworkRequestV2(AidlNetworkRequest.java:172)
at com.nextcloud.android.sso.api.NextcloudAPI.performNetworkRequestV2(NextcloudAPI.java:171)
at com.nextcloud.android.sso.api.NextcloudAPI.lambda$performRequestObservableV2$1$NextcloudAPI(NextcloudAPI.java:110)
at com.nextcloud.android.sso.api.NextcloudAPI$$ExternalSyntheticLambda0.subscribe(Unknown Source:6)
at io.reactivex.internal.operators.observable.ObservableFromPublisher.subscribeActual(ObservableFromPublisher.java:31)
at io.reactivex.Observable.subscribe(Observable.java:12284)
at io.reactivex.internal.operators.observable.ObservableMap.subscribeActual(ObservableMap.java:32)
at io.reactivex.Observable.subscribe(Observable.java:12284)
at io.reactivex.internal.operators.observable.ObservableSubscribeOn$SubscribeTask.run(ObservableSubscribeOn.java:96)
at io.reactivex.internal.schedulers.ScheduledDirectTask.call(ScheduledDirectTask.java:38)
at io.reactivex.internal.schedulers.ScheduledDirectTask.call(ScheduledDirectTask.java:26)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
at java.lang.Thread.run(Thread.java:923)
Caused by: java.lang.IllegalStateException: {"status":500,"message":"Die hochgeladene Datei \u00fcberschreitet die upload_max_filesize-Vorgabe in php.ini"}

at com.nextcloud.android.sso.InputStreamBinder.processRequestV2(InputStreamBinder.java:429)
at com.nextcloud.android.sso.InputStreamBinder.performNextcloudRequestAndBodyStreamV2(InputStreamBinder.java:125)
at com.nextcloud.android.sso.aidl.IInputStreamService$Stub.onTransact(IInputStreamService.java:137)
at android.os.Binder.execTransactInternal(Binder.java:1195)
at android.os.Binder.execTransact(Binder.java:1159)
```

Best
Henning

**Comment by stefan-niedermann** [comment]
The interesting part is here:

> Die hochgeladene Datei \u00fcberschreitet die upload_max_filesize-Vorgabe in php.ini

Have you checked your settings on your server?

**Comment by stefan-niedermann** [comment]
By the way: Please note that this repository is only for issues regarding the Deck server app. In the future please report issues regarding the Deck Android app here: https://github.com/stefan-niedermann/nextcloud-deck/issues

**Comment by henningaround** [comment]
Thank you Stefan. You helped me reading this message! I guess now it's obvious. I will check and report.

**Comment by CedricNdong** [comment]
Hello.  I also have the same problem.  How have you resolved it? 

I upgraded to nextcloud 30

Using deck on android ( Google pixel 7)

**Comment by CedricNdong** [comment]
> OK solved!

?

**Comment by henningaround** [comment]
Yes, you have to adjust upload_max_filesize in php.ini

**Comment by CedricNdong** [comment]
I already have there 30G

**Comment by henningaround** [comment]
I think 30G as upload_max_filesize in your php.ini is not a good choice, but my knowledge is very basic. Maybe you should open a new issue as this one here is related to specific versions and it has been said that it is not related to the server app but the android app here:
https://github.com/stefan-niedermann/nextcloud-deck/issues
