### ISSUE TITLE
onSaveInstanceState

### ISSUE THREAD

**Issue by ristein** [nextcloud/deck#3617]
new user here.
after I set up Deck app I changed something online and app would not sync anymore.
after account delete and reconnect empty (no cards).
after app reset and trying to log in this error.
What can I do?

using LineageOs4MicroG

```
Full Crash:

App Version: 1.20.0
App Version Code: 1020000
App Flavor: fdroid

Files App Version Code: 30190090

---

OS Version: 4.14.190-perf+(eng.root.20220303.115310)
OS API Level: 30
Device: OnePlus7Pro
Manufacturer: OnePlus
Model (and Product): GM1917 (OnePlus7Pro)

---

java.lang.IllegalStateException: Can not perform this action after onSaveInstanceState
	at androidx.fragment.app.FragmentManager.checkStateLoss(FragmentManager.java:1844)
	at androidx.fragment.app.FragmentManager.enqueueAction(FragmentManager.java:1884)
	at androidx.fragment.app.BackStackRecord.commitInternal(BackStackRecord.java:329)
	at androidx.fragment.app.BackStackRecord.commit(BackStackRecord.java:294)
	at androidx.fragment.app.DialogFragment.show(DialogFragment.java:260)
	at it.niedermann.nextcloud.deck.ui.ImportAccountActivity$1$1$1.lambda$onError$4$it-niedermann-nextcloud-deck-ui-ImportAccountActivity$1$1$1(ImportAccountActivity.java:184)
	at it.niedermann.nextcloud.deck.ui.ImportAccountActivity$1$1$1$$ExternalSyntheticLambda4.run(Unknown Source:6)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7664)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)

```

**Comment by stefan-niedermann** [comment]
> after I set up Deck app I changed something online and app would not sync anymore.

Very likely caused by not updated `ETags` (unfortunately there are [quite a lot of issues in the Deck server app](https://github.com/nextcloud/deck/issues?q=is%3Aissue+is%3Aopen+etag) regarding this topic)...

> after app reset and trying to log in this error.

Try clearing the storage of the Deck android app [as described in our FAQ](https://github.com/stefan-niedermann/nextcloud-deck/blob/master/FAQ.md#i-have-experienced-an-error) and import your account again.

By the way, this is the repository of the Deck server app, in case the issue persists, please open a new issue in the [repository of the Deck Android app](https://github.com/stefan-niedermann/nextcloud-deck/issues/new/choose) (filling the complete issue template).
