### ISSUE TITLE
Migrate DECK to another NextCloud instance

### ISSUE THREAD

**Issue by speedAmaster** [nextcloud/deck#3709]
is there any possibility to export DECKs (incl attachments) from one instance and import to another NextCloud instance?

**Comment by aleadco** [comment]
We are having this need too. We need to migrate to a new NC instance but we didn't want to lose the created projects. It would be a great feature...

**Comment by stefan-niedermann** [comment]
@RainerKlute please don't mix up topics: An export for being GPDR complient is already available via an [`occ` command](https://open-netlab.de/nextcloud-v21-02-occ-commands/).

**Comment by RainerKlute** [comment]
Not sure what you are talking about, @stefan-niedermann. Which occ command would that be? Following your link, I can neither find the word “GDPR” nor “personal” nor “protection”.
Besides, how should that occ command know whether/what data I am processing in some board are _personal_ data?

**Comment by stefan-niedermann** [comment]
@RainerKlute try searching for `deck` 😉 Also linking to the [help forum, where this topic has also been answered](https://help.nextcloud.com/t/nextcloud-deck-delivers-file-attachments-checkboxes-and-export/34051/6).

**Comment by RainerKlute** [comment]
Unfortunately the `occ deck:export some.user` command throws an exception, whether `some.user` is a existing user ID or not.

```The process control (PCNTL) extensions are required in case you want to interrupt long running commands - see https://www.php.net/manual/en/book.pcntl.php
An unhandled exception has been thrown:
TypeError: Argument 1 passed to OC\Group\Manager::getUserIdGroupIds() must be of the type string, null given, called in /data/nextcloud/lib/private/Group/Manager.php on line 310 and defined in /data/nextcloud/lib/private/Group/Manager.php:327
Stack trace:
#0 /data/nextcloud/lib/private/Group/Manager.php(310): OC\Group\Manager->getUserIdGroupIds()
#1 /data/nextcloud/apps/deck/lib/Service/PermissionService.php(227): OC\Group\Manager->isInGroup()
#2 /data/nextcloud/apps/deck/lib/Service/PermissionService.php(122): OCA\Deck\Service\PermissionService->userCan()
#3 /data/nextcloud/apps/deck/lib/Service/BoardService.php(157): OCA\Deck\Service\PermissionService->matchPermissions()
#4 /data/nextcloud/apps/deck/lib/Command/UserExport.php(90): OCA\Deck\Service\BoardService->findAll()
#5 /data/nextcloud/3rdparty/symfony/console/Command/Command.php(255): OCA\Deck\Command\UserExport->execute()
#6 /data/nextcloud/3rdparty/symfony/console/Application.php(1009): Symfony\Component\Console\Command\Command->run()
#7 /data/nextcloud/3rdparty/symfony/console/Application.php(273): Symfony\Component\Console\Application->doRunCommand()
#8 /data/nextcloud/3rdparty/symfony/console/Application.php(149): Symfony\Component\Console\Application->doRun()
#9 /data/nextcloud/lib/private/Console/Application.php(211): Symfony\Component\Console\Application->run()
#10 /data/nextcloud/console.php(99): OC\Console\Application->run()
#11 /data/nextcloud/occ(11): require_once('/data/nextcloud...')
#12 {main}```

**Comment by juliushaertl** [comment]
I filed #3828 with more details on how the implementation should be handled since there is now a server API for this with 24. Let's use this one for tracking.
