### ISSUE TITLE
make build fails with Error: Cannot find module 'vue-loader'

### ISSUE THREAD

**Issue by reos-rcrozier** [nextcloud/deck#3849]
**Describe the bug**
Running the suggested setup sequence (i.e. `make install-deps` followed by `make build`  results in an error.

```
> deck@1.7.0 build /home/rcrozier/src/nextcloud-deck
> NODE_ENV=production webpack --progress --config webpack.js

/usr/share/nodejs/webpack/node_modules/webpack-cli/bin/cli.js:93
				throw err;
				^

Error: Cannot find module 'vue-loader'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (/usr/share/nodejs/webpack/node_modules/v8-compile-cache/v8-compile-cache.js:161:20)
    at Object.<anonymous> (/home/rcrozier/src/nextcloud-deck/node_modules/@nextcloud/webpack-vue-config/webpack.config.js:26:29)
    at Module._compile (/usr/share/nodejs/webpack/node_modules/v8-compile-cache/v8-compile-cache.js:194:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (/usr/share/nodejs/webpack/node_modules/v8-compile-cache/v8-compile-cache.js:161:20)
    at Object.<anonymous> (/home/rcrozier/src/nextcloud-deck/node_modules/@nextcloud/webpack-vue-config/index.js:23:18)
    at Module._compile (/usr/share/nodejs/webpack/node_modules/v8-compile-cache/v8-compile-cache.js:194:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (/usr/share/nodejs/webpack/node_modules/v8-compile-cache/v8-compile-cache.js:161:20)
    at Object.<anonymous> (/home/rcrozier/src/nextcloud-deck/webpack.js:1:85)
    at Module._compile (/usr/share/nodejs/webpack/node_modules/v8-compile-cache/v8-compile-cache.js:194:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (/usr/share/nodejs/webpack/node_modules/v8-compile-cache/v8-compile-cache.js:161:20)
    at WEBPACK_OPTIONS (/usr/share/nodejs/webpack/node_modules/webpack-cli/bin/utils/convert-argv.js:114:13)
    at requireConfig (/usr/share/nodejs/webpack/node_modules/webpack-cli/bin/utils/convert-argv.js:116:6)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! deck@1.7.0 build: `NODE_ENV=production webpack --progress --config webpack.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the deck@1.7.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/rcrozier/.npm/_logs/2022-05-30T22_36_54_538Z-debug.log
make: *** [Makefile:34: build-js] Error 1

```

**To Reproduce**

```
git clone git@github.com:nextcloud/deck.git
cd deck
make install-deps 
make build
```

**Expected behavior**
Build completes without error

**Client details:**
 - OS: Mint Linux 20
 - Device: desktop

**Comment by reos-rcrozier** [comment]
I just needed to install this (and then many more) missing modules, like in this script:

```
npm i vue-loader@15.9.8 -D
npm install node-polyfill-webpack-plugin
npm i terser-webpack-plugin
npm i webpack
npm i babel
npm i babel-loader
npm install --save-dev @babel/plugin-syntax-dynamic-import
npm install --save-dev @babel/preset-env
npm install ical.js
npm install css-loader
npm install sass-loader
npm install sass
```
