### ISSUE TITLE
Creating a new board with a too long title yields a DB error

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/deck#4002]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

The error should be prevented so that users can not post too big data against the DB.

Use this as board name for testing:

```
Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lore
```

```
Technical details

    Remote Address: ::1
    Request ID: YwixtzO3XrTZ3svw5yYSqwAAAAE
    Type: OC\DB\Exceptions\DbalException
    Code: 1406
    Message: An exception occurred while executing a query: SQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'title' at row 1
    File: /home/nickv/Nextcloud/25/server/lib/private/DB/Exceptions/DbalException.php
    Line: 71


Trace

#0 /home/nickv/Nextcloud/25/server/lib/private/DB/QueryBuilder/QueryBuilder.php(329): OC\DB\Exceptions\DbalException::wrap()
#1 /home/nickv/Nextcloud/25/server/lib/public/AppFramework/Db/QBMapper.php(139): OC\DB\QueryBuilder\QueryBuilder->executeStatement()
#2 /home/nickv/Nextcloud/25/server/appssubscriptions/deck/lib/Service/BoardService.php(317): OCP\AppFramework\Db\QBMapper->insert()
#3 /home/nickv/Nextcloud/25/server/appssubscriptions/deck/lib/Controller/BoardController.php(70): OCA\Deck\Service\BoardService->create()
#4 /home/nickv/Nextcloud/25/server/lib/private/AppFramework/Http/Dispatcher.php(225): OCA\Deck\Controller\BoardController->create()
#5 /home/nickv/Nextcloud/25/server/lib/private/AppFramework/Http/Dispatcher.php(133): OC\AppFramework\Http\Dispatcher->executeController()
#6 /home/nickv/Nextcloud/25/server/lib/private/AppFramework/App.php(172): OC\AppFramework\Http\Dispatcher->dispatch()
#7 /home/nickv/Nextcloud/25/server/lib/private/Route/Router.php(298): OC\AppFramework\App::main()
#8 /home/nickv/Nextcloud/25/server/lib/base.php(1042): OC\Route\Router->match()
#9 /home/nickv/Nextcloud/25/server/index.php(36): OC::handleRequest()
#10 {main}


Previous

#0 /home/nickv/Nextcloud/25/server/3rdparty/doctrine/dbal/src/Connection.php(1780): Doctrine\DBAL\Driver\API\MySQL\ExceptionConverter->convert()
#1 /home/nickv/Nextcloud/25/server/3rdparty/doctrine/dbal/src/Connection.php(1719): Doctrine\DBAL\Connection->handleDriverException()
#2 /home/nickv/Nextcloud/25/server/3rdparty/doctrine/dbal/src/Connection.php(1173): Doctrine\DBAL\Connection->convertExceptionDuringQuery()
#3 /home/nickv/Nextcloud/25/server/lib/private/DB/Connection.php(294): Doctrine\DBAL\Connection->executeStatement()
#4 /home/nickv/Nextcloud/25/server/3rdparty/doctrine/dbal/src/Query/QueryBuilder.php(354): OC\DB\Connection->executeStatement()
#5 /home/nickv/Nextcloud/25/server/lib/private/DB/QueryBuilder/QueryBuilder.php(281): Doctrine\DBAL\Query\QueryBuilder->execute()
#6 /home/nickv/Nextcloud/25/server/lib/private/DB/QueryBuilder/QueryBuilder.php(327): OC\DB\QueryBuilder\QueryBuilder->execute()
#7 /home/nickv/Nextcloud/25/server/lib/public/AppFramework/Db/QBMapper.php(139): OC\DB\QueryBuilder\QueryBuilder->executeStatement()
#8 /home/nickv/Nextcloud/25/server/appssubscriptions/deck/lib/Service/BoardService.php(317): OCP\AppFramework\Db\QBMapper->insert()
#9 /home/nickv/Nextcloud/25/server/appssubscriptions/deck/lib/Controller/BoardController.php(70): OCA\Deck\Service\BoardService->create()
#10 /home/nickv/Nextcloud/25/server/lib/private/AppFramework/Http/Dispatcher.php(225): OCA\Deck\Controller\BoardController->create()
#11 /home/nickv/Nextcloud/25/server/lib/private/AppFramework/Http/Dispatcher.php(133): OC\AppFramework\Http\Dispatcher->executeController()
#12 /home/nickv/Nextcloud/25/server/lib/private/AppFramework/App.php(172): OC\AppFramework\Http\Dispatcher->dispatch()
#13 /home/nickv/Nextcloud/25/server/lib/private/Route/Router.php(298): OC\AppFramework\App::main()
#14 /home/nickv/Nextcloud/25/server/lib/base.php(1042): OC\Route\Router->match()
#15 /home/nickv/Nextcloud/25/server/index.php(36): OC::handleRequest()
#16 {main}


Previous

#0 /home/nickv/Nextcloud/25/server/3rdparty/doctrine/dbal/src/Driver/PDO/Statement.php(94): Doctrine\DBAL\Driver\PDO\Exception::new()
#1 /home/nickv/Nextcloud/25/server/3rdparty/doctrine/dbal/src/Connection.php(1163): Doctrine\DBAL\Driver\PDO\Statement->execute()
#2 /home/nickv/Nextcloud/25/server/lib/private/DB/Connection.php(294): Doctrine\DBAL\Connection->executeStatement()
#3 /home/nickv/Nextcloud/25/server/3rdparty/doctrine/dbal/src/Query/QueryBuilder.php(354): OC\DB\Connection->executeStatement()
#4 /home/nickv/Nextcloud/25/server/lib/private/DB/QueryBuilder/QueryBuilder.php(281): Doctrine\DBAL\Query\QueryBuilder->execute()
#5 /home/nickv/Nextcloud/25/server/lib/private/DB/QueryBuilder/QueryBuilder.php(327): OC\DB\QueryBuilder\QueryBuilder->execute()
#6 /home/nickv/Nextcloud/25/server/lib/public/AppFramework/Db/QBMapper.php(139): OC\DB\QueryBuilder\QueryBuilder->executeStatement()
#7 /home/nickv/Nextcloud/25/server/appssubscriptions/deck/lib/Service/BoardService.php(317): OCP\AppFramework\Db\QBMapper->insert()
#8 /home/nickv/Nextcloud/25/server/appssubscriptions/deck/lib/Controller/BoardController.php(70): OCA\Deck\Service\BoardService->create()
#9 /home/nickv/Nextcloud/25/server/lib/private/AppFramework/Http/Dispatcher.php(225): OCA\Deck\Controller\BoardController->create()
#10 /home/nickv/Nextcloud/25/server/lib/private/AppFramework/Http/Dispatcher.php(133): OC\AppFramework\Http\Dispatcher->executeController()
#11 /home/nickv/Nextcloud/25/server/lib/private/AppFramework/App.php(172): OC\AppFramework\Http\Dispatcher->dispatch()
#12 /home/nickv/Nextcloud/25/server/lib/private/Route/Router.php(298): OC\AppFramework\App::main()
#13 /home/nickv/Nextcloud/25/server/lib/base.php(1042): OC\Route\Router->match()
#14 /home/nickv/Nextcloud/25/server/index.php(36): OC::handleRequest()
#15 {main}


Previous

#0 /home/nickv/Nextcloud/25/server/3rdparty/doctrine/dbal/src/Driver/PDO/Statement.php(92): PDOStatement->execute()
#1 /home/nickv/Nextcloud/25/server/3rdparty/doctrine/dbal/src/Connection.php(1163): Doctrine\DBAL\Driver\PDO\Statement->execute()
#2 /home/nickv/Nextcloud/25/server/lib/private/DB/Connection.php(294): Doctrine\DBAL\Connection->executeStatement()
#3 /home/nickv/Nextcloud/25/server/3rdparty/doctrine/dbal/src/Query/QueryBuilder.php(354): OC\DB\Connection->executeStatement()
#4 /home/nickv/Nextcloud/25/server/lib/private/DB/QueryBuilder/QueryBuilder.php(281): Doctrine\DBAL\Query\QueryBuilder->execute()
#5 /home/nickv/Nextcloud/25/server/lib/private/DB/QueryBuilder/QueryBuilder.php(327): OC\DB\QueryBuilder\QueryBuilder->execute()
#6 /home/nickv/Nextcloud/25/server/lib/public/AppFramework/Db/QBMapper.php(139): OC\DB\QueryBuilder\QueryBuilder->executeStatement()
#7 /home/nickv/Nextcloud/25/server/appssubscriptions/deck/lib/Service/BoardService.php(317): OCP\AppFramework\Db\QBMapper->insert()
#8 /home/nickv/Nextcloud/25/server/appssubscriptions/deck/lib/Controller/BoardController.php(70): OCA\Deck\Service\BoardService->create()
#9 /home/nickv/Nextcloud/25/server/lib/private/AppFramework/Http/Dispatcher.php(225): OCA\Deck\Controller\BoardController->create()
#10 /home/nickv/Nextcloud/25/server/lib/private/AppFramework/Http/Dispatcher.php(133): OC\AppFramework\Http\Dispatcher->executeController()
#11 /home/nickv/Nextcloud/25/server/lib/private/AppFramework/App.php(172): OC\AppFramework\Http\Dispatcher->dispatch()
#12 /home/nickv/Nextcloud/25/server/lib/private/Route/Router.php(298): OC\AppFramework\App::main()
#13 /home/nickv/Nextcloud/25/server/lib/base.php(1042): OC\Route\Router->match()
#14 /home/nickv/Nextcloud/25/server/index.php(36): OC::handleRequest()
#15 {main}

[Nextcloud](https://nextcloud.com/) – a safe home for all your data
```

**Comment by DJE98** [comment]
# Step by step reproduction of the bug with web interface

## Create card with long text

![Screenshot 2022-10-19 at 21-24-27 Personal - Deck - Nextcloud](https://user-images.githubusercontent.com/73851419/196787767-5c178b0f-c1b9-4711-b93d-91731dd6352e.png)

## Get message with length limitation of the title

![Screenshot 2022-10-19 at 21-24-46 Personal - Deck - Nextcloud](https://user-images.githubusercontent.com/73851419/196788013-152edd6e-0859-4b9f-8a4d-3b923e98f5e8.png)

Note: I expected to get no feedback about the length limitation or an error on the server side.

**Comment by DJE98** [comment]
# Step by Step reproduction of the error on api level

## Send request with long name

́́̀```
curl -u admin:admin -X POST -H "Content-Type: application/json" \
    -d '{"title": "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lore"}'\
    'http://nextcloud.local/index.php/apps/deck/api/v1.0/boards/1/stacks/1/cards' \
    -H "OCS-APIRequest: true" \                          
    -H "If-Modified-Since: Mon, 05 Nov 2018 09:28:00 GMT"
́́̀```

## Get message with length limitation of the title

́́̀```
{"status":400,"message":"The title cannot exceed 255 characters"}  
́́̀```

Note: I expected to get no feedback about the length limitation or an error on the server side.

**Comment by DJE98** [comment]
Thank you for reporting the problem. Can you give us more information to reproduce the problem? Do you tested your problem on the current master branch version or on the last deck release 1.7? Thank your in answer for your time.

**Comment by juliushaertl** [comment]
The issue report was about creating a new board, which would get addressed in #4059
