### ISSUE TITLE
`occ deck:export some.user` errors out

### ISSUE THREAD

**Issue by KiaraGrouwstra** [nextcloud/deck#4010]
Unfortunately the `occ deck:export some.user` command throws an exception, whether `some.user` is a existing user ID or not.

```The process control (PCNTL) extensions are required in case you want to interrupt long running commands - see https://www.php.net/manual/en/book.pcntl.php
An unhandled exception has been thrown:
TypeError: Argument 1 passed to OC\Group\Manager::getUserIdGroupIds() must be of the type string, null given, called in /data/nextcloud/lib/private/Group/Manager.php on line 310 and defined in /data/nextcloud/lib/private/Group/Manager.php:327
Stack trace:
#0 /data/nextcloud/lib/private/Group/Manager.php(310): OC\Group\Manager->getUserIdGroupIds()
#1 /data/nextcloud/apps/deck/lib/Service/PermissionService.php(227): OC\Group\Manager->isInGroup()
#2 /data/nextcloud/apps/deck/lib/Service/PermissionService.php(122): OCA\Deck\Service\PermissionService->userCan()
#3 /data/nextcloud/apps/deck/lib/Service/BoardService.php(157): OCA\Deck\Service\PermissionService->matchPermissions()
#4 /data/nextcloud/apps/deck/lib/Command/UserExport.php(90): OCA\Deck\Service\BoardService->findAll()
#5 /data/nextcloud/3rdparty/symfony/console/Command/Command.php(255): OCA\Deck\Command\UserExport->execute()
#6 /data/nextcloud/3rdparty/symfony/console/Application.php(1009): Symfony\Component\Console\Command\Command->run()
#7 /data/nextcloud/3rdparty/symfony/console/Application.php(273): Symfony\Component\Console\Application->doRunCommand()
#8 /data/nextcloud/3rdparty/symfony/console/Application.php(149): Symfony\Component\Console\Application->doRun()
#9 /data/nextcloud/lib/private/Console/Application.php(211): Symfony\Component\Console\Application->run()
#10 /data/nextcloud/console.php(99): OC\Console\Application->run()
#11 /data/nextcloud/occ(11): require_once('/data/nextcloud...')
#12 {main}
```

_Originally posted by @RainerKlute in https://github.com/nextcloud/deck/issues/3709#issuecomment-1127019055_

my own nextcloud version: 24.0.3

**Comment by avvertix** [comment]
I also experienced this today. I found that one of the boards owned by the users was shared with a group. Unsharing the board resolved the problem and allowed me to continue the export.
