### ISSUE TITLE
external app sync breaks: "Not a JSON Object: 105"

### ISSUE THREAD

**Issue by gergolippai** [nextcloud/deck#4591]
hi, recently (~1 week, but maybe more) my deck app on my nextcloud server stopped working with both the deck ios app and android app, and i'm wondering what the cause could be. looks like the nextcloud server somehow returns broken JSON to the app?...

before I paste the error log, some add'l crosscheck i did:
1. tried all possible deck apps to see if any of them work (or, to validate that none of them work): deck ng and the deck app on ios, and the deck app on Android. I tested on iPhone, an Android tablet and an Android phone. none of them worked. (which is why i'm posting this here and not respective app githubs - seems like a server issue and not a particular app issue.)
2. tried cross testing across multiple users: 2 live users with existing deck data, and a brand new test user with an empty deck on the same instance. none of them worked.
3. tried cross testing with another version of Nextcloud: Nextcloud 24.0.11 + deck 1.7.3 (both latest in their respective branches when i write this) does *not* work; Nextcloud 25.0.5 + deck 1.8.3 combo *does* work. (for reasons I can not yet upgrade my NC24 instance.)

although the iOS app does not give any useful error msg, the Android one does - I'm using that below for the bug report.
NC version: 24.0.11
deck version: 1.7.3

error log in the app:
```
App Version: 1.21.8
App Version Code: 1021008
Server App Version: 1.7.3
App Flavor: fdroid

Files App Version Code: 30240190

---

OS Version: 4.14.186-gaf81b6b5337d(TB125FU_USR_S000160_2302271447_MP1RC_ROW)
OS API Level: 31
Device: TB125FU
Manufacturer: LENOVO
Model (and Product): Lenovo TB125FU (TB125FU_EEA)

---

com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Not a JSON Object: 105
	at com.google.gson.Gson.fromJson(Gson.java:1238)
	at com.google.gson.Gson.fromJson(Gson.java:1137)
	at com.google.gson.Gson.fromJson(Gson.java:1107)
	at com.nextcloud.android.sso.api.NextcloudAPI.convertStreamToTargetEntity(NextcloudAPI.java:159)
	at com.nextcloud.android.sso.api.NextcloudAPI.lambda$performRequestObservableV2$1$com-nextcloud-android-sso-api-NextcloudAPI(NextcloudAPI.java:130)
	at com.nextcloud.android.sso.api.NextcloudAPI$$ExternalSyntheticLambda0.subscribe(Unknown Source:6)
	at io.reactivex.internal.operators.observable.ObservableFromPublisher.subscribeActual(ObservableFromPublisher.java:31)
	at io.reactivex.Observable.subscribe(Observable.java:12284)
	at io.reactivex.internal.operators.observable.ObservableSubscribeOn$SubscribeTask.run(ObservableSubscribeOn.java:96)
	at io.reactivex.internal.schedulers.ScheduledDirectTask.call(ScheduledDirectTask.java:38)
	at io.reactivex.internal.schedulers.ScheduledDirectTask.call(ScheduledDirectTask.java:26)
	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
	at java.lang.Thread.run(Thread.java:1012)
Caused by: java.lang.IllegalStateException: Not a JSON Object: 105
	at com.google.gson.JsonElement.getAsJsonObject(JsonElement.java:101)
	at it.niedermann.nextcloud.deck.api.NextcloudArrayDeserializer.deserialize(NextcloudArrayDeserializer.java:35)
	at it.niedermann.nextcloud.deck.api.NextcloudArrayDeserializer.deserialize(NextcloudArrayDeserializer.java:18)
	at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:76)
	at com.google.gson.Gson.fromJson(Gson.java:1227)
	... 14 more

```

from what I could see, nextloud.log did not capture any error for this request.

thanks in advance for any pointers/help!

**Comment by stefan-niedermann** [comment]
Hey, the issue is caused by Rainloop and / or SnappyMail. Uninstall them to make the API work again. Issue is **not** caused by Deck as all other REST APIs are affected as well (like Notes, News, Bookmarks, Cookbook, ...) and can therefore not be fixed here.

See also https://github.com/nextcloud/notes-android/issues/1683#issuecomment-1429296149

**Comment by gergolippai** [comment]
thanks for the reply, indeed this solved it 👍
(one additional note: on Nextcloud 25.0.5 + Snappymail install the issue is *not* there anymore, so apparently in newer versions it's fixed.)
