### ISSUE TITLE
occ deck:export error (fixed one year ago?)

### ISSUE THREAD

**Issue by t-markmann** [nextcloud/deck#5028]
I wanted to use the deck export feature.
The resulting bug has already occured a year ago and has been fixed. Unfortunately in one of my instances, this error still occurs. 

Related: https://github.com/nextcloud/deck/issues/4010

Error message:

An unhandled exception has been thrown:
TypeError: OC\Group\Manager::getUserIdGroupIds(): Argument #1 ($uid) must be of type string, null given, called in /zfsinst/ed_instances/mynextcloud/lib/private/Group/Manager.php on line 315 and defined in /zfsinst/ed_instances/mynextcloud/lib/private/Group/Manager.php:332
Stack trace:
#0 /zfsinst/ed_instances/mynextcloud/lib/private/Group/Manager.php(315): OC\Group\Manager->getUserIdGroupIds()
#1 /zfsinst/ed_instances/mynextcloud/apps/deck/lib/Service/PermissionService.php(227): OC\Group\Manager->isInGroup()
#2 /zfsinst/ed_instances/mynextcloud/apps/deck/lib/Service/PermissionService.php(134): OCA\Deck\Service\PermissionService->userCan()
#3 /zfsinst/ed_instances/mynextcloud/apps/deck/lib/Service/BoardService.php(658): OCA\Deck\Service\PermissionService->matchPermissions()
#4 /zfsinst/ed_instances/mynextcloud/apps/deck/lib/Service/BoardService.php(164): OCA\Deck\Service\BoardService->enrichBoards()
#5 /zfsinst/ed_instances/mynextcloud/apps/deck/lib/Command/UserExport.php(91): OCA\Deck\Service\BoardService->findAll()
#6 /zfsinst/ed_instances/mynextcloud/3rdparty/symfony/console/Command/Command.php(255): OCA\Deck\Command\UserExport->execute()
#7 /zfsinst/ed_instances/mynextcloud/3rdparty/symfony/console/Application.php(1009): Symfony\Component\Console\Command\Command->run()
#8 /zfsinst/ed_instances/mynextcloud/3rdparty/symfony/console/Application.php(273): Symfony\Component\Console\Application->doRunCommand()
#9 /zfsinst/ed_instances/mynextcloud/3rdparty/symfony/console/Application.php(149): Symfony\Component\Console\Application->doRun()
#10 /zfsinst/ed_instances/mynextcloud/lib/private/Console/Application.php(211): Symfony\Component\Console\Application->run()
#11 /zfsinst/ed_instances/mynextcloud/console.php(100): OC\Console\Application->run()
#12 /zfsinst/ed_instances/mynextcloud/occ(11): require_once('...')
#13 {main}

Server and Nextcloud details:

## Server configuration detail

**Operating system:** Linux 5.4.0-125-generic #141-Ubuntu SMP Wed Aug 10 13:42:03 UTC 2022 x86_64

**Webserver:** Apache/2.4.52 (Ubuntu) (apache2handler)

**Database:** mysql 8.0.33

**PHP version:** 8.0.15

Modules loaded: Core, date, libxml, openssl, pcre, zlib, filter, hash, json, Reflection, SPL, session, standard, sodium, apache2handler, mysqlnd, PDO, xml, apcu, calendar, ctype, curl, dom, mbstring, FFI, fileinfo, ftp, gd, gettext, gmp, iconv, igbinary, imagick, intl, ldap, exif, mysqli, pdo_mysql, Phar, posix, readline, redis, shmop, SimpleXML, sockets, sysvmsg, sysvsem, sysvshm, tokenizer, xmlreader, xmlwriter, xsl, zip, Zend OPcache

**Nextcloud version:** 26.0.5 - 26.0.5.1

**Updated from an older Nextcloud/ownCloud or fresh install:** Older NC

**Where did you install Nextcloud from:** from zip file

<details><summary>Signing status</summary>

Integrity checker has been disabled. Integrity cannot be verified.
</details>

<details><summary>List of activated apps</summary>

```
Enabled:
 - activity: 2.18.0
 - admin_audit: 1.16.0
 - auto_groups: 1.5.2
 - breezedark: 26.0.0
 - bruteforcesettings: 2.6.0
 - calendar: 4.4.4
 - circles: 26.0.0
 - cloud_federation_api: 1.9.0
 - comments: 1.16.0
 - contacts: 5.3.2
 - contactsinteraction: 1.7.0
 - dashboard: 7.6.0
 - data_request: 1.13.0
 - dav: 1.25.0
 - deck: 1.9.2
 - drawio: 2.1.2
 - drop_account: 2.2.0
 - federatedfilesharing: 1.16.0
 - federation: 1.16.0
 - files: 1.21.1
 - files_fulltextsearch: 26.0.1
 - files_linkeditor: 1.1.16
 - files_mindmap: 0.0.28
 - files_pdfviewer: 2.7.0
 - files_rightclick: 1.5.0
 - files_sharing: 1.18.0
 - files_trashbin: 1.16.0
 - files_versions: 1.19.1
 - forms: 3.3.1
 - groupfolders: 14.0.4
 - impersonate: 1.13.1
 - keeweb: 0.6.13
 - logreader: 2.11.0
 - lookup_server_connector: 1.14.0
 - notifications: 2.14.0
 - oauth2: 1.14.1
 - occweb: 0.1.0
 - password_policy: 1.16.0
 - photos: 2.2.0
 - polls: 5.2.0
 - privacy: 1.10.0
 - provisioning_api: 1.16.0
 - related_resources: 1.1.0
 - richdocuments: 8.0.3
 - settings: 1.8.0
 - sharebymail: 1.16.0
 - support: 1.9.0
 - systemtags: 1.16.0
 - tasks: 0.15.0
 - text: 3.7.2
 - theming: 2.1.1
 - twofactor_backupcodes: 1.15.0
 - user_saml: 5.2.2
 - user_status: 1.6.0
 - viewer: 1.10.0
 - weather_status: 1.6.0
 - workflow_pdf_converter: 1.11.0
 - workflowengine: 2.8.0
Disabled:
 - encryption
 - files_external
 - firstrunwizard: 2.5.0
 - nextcloud_announcements: 1.6.0
 - pdf_downloader: 1.1.3
 - recommendations: 0.4.0
 - serverinfo: 1.7.0
 - survey_client: 1.5.0
 - suspicious_login
 - theming_customcss: 1.14.0
 - twofactor_totp
 - updatenotification: 1.7.0
 - user_ldap

```
</details>

<details><summary>Configuration (config/config.php)</summary>

```
{
    "forwarded_for_headers": [
        "HTTP_X_FORWARDED_FOR"
    ],
    "installed": true,
    "default_language": "de",
    "overwriteprotocol": "https",
    "forcessl": true,
    "memcache.locking": "\\OC\\Memcache\\Redis",
    "redis": {
        "host": "***REMOVED SENSITIVE VALUE***",
        "port": 6379
    },
    "skeletondirectory": "\/home\/ed\/Sync\/skeleton",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "datadirectory": "***REMOVED SENSITIVE VALUE***",
    "dbtype": "mysql",
    "version": "26.0.5.1",
    "overwrite.cli.url": "https:\/\/four.parted.fqdn.de",
    "dbname": "***REMOVED SENSITIVE VALUE***",
    "dbhost": "***REMOVED SENSITIVE VALUE***",
    "dbport": "3306",
    "dbtableprefix": "oc_",
    "mysql.utf8mb4": true,
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "instanceid": "***REMOVED SENSITIVE VALUE***",
    "htaccess.RewriteBase": "\/",
    "simpleSignUpLink.shown": false,
    "updater.release.channel": "stable",
    "integrity.check.disabled": true,
    "memcache.local": "\\OC\\Memcache\\APCu",
    "mail_from_address": "***REMOVED SENSITIVE VALUE***",
    "mail_sendmailmode": "pipe",
    "mail_smtpmode": "sendmail",
    "mail_domain": "***REMOVED SENSITIVE VALUE***",
    "logfile": "\/var\/www\/nc-logs\/mynextcloud.log",
    "allow_user_to_change_display_name": false,
    "maintenance": false,
    "default_locale": "de_DE",
    "activity_expire_days": 365,
    "trusted_proxies": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "four.parted.fqdn.de"
    ],
    "app_install_overwrite": [
        "occweb"
    ]
}
```
</details>

**Cron Configuration:** Array
(
    [backgroundjobs_mode] => cron
    [lastcron] => 1692084326
)

**External storages:** files_external is disabled

**Encryption:** no

**User-backends:** 
 * OC\User\Database
 * OCA\User_SAML\UserBackend

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/116.0

**Comment by t-markmann** [comment]
It works again in NC26.0.7.0
