### ISSUE TITLE
Loosing focus when editing the description in a card

### ISSUE THREAD

**Issue by arnowelzel** [nextcloud/deck#6528]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Describe the bug**
When I open a card to add a description, the card will be saved automatically as soon as I stop typing. However in this moment the focus of the text editor gets lost and instead the title is focused. This is very confusing since you do not expect that the cursor suddenly jumps from the text editor to the title.

**To Reproduce**
1. Create a new card.
2. Open the card.
3. Click the "Description" field and type something.
4. When the card is saved, it can happen, that the focus is lost and jumps to the title.

**Expected behavior**
The focus should always stay where it is and must not be changed without user interaction to change it intentionally.

**Screenshots**
![Image](https://github.com/user-attachments/assets/153a51a9-64ab-4c5f-9584-97a50361fbb8)

**Client details:**
 - OS: Windows 11
 - Browser: Vivaldi, Chrome, Firefox, Edge
 - Version: Latestt versions as of 2024-11-22
 - Device: Desktop

<details>
<summary>Server details</summary>

**Operating system**:

**Web server:**

**Database:**

**PHP version:**

**Nextcloud version:** (see Nextcloud admin page)

**Where did you install Nextcloud from:**

**Signing status:**

```
No errors have been found.
```

**List of activated apps:**

```
Enabled:
  - activity: 3.0.0
  - admin_audit: 1.20.0
  - app_api: 4.0.0
  - bruteforcesettings: 3.0.0
  - calendar: 5.0.5
  - circles: 30.0.0
  - cloud_federation_api: 1.13.0
  - collectives: 2.15.1
  - comments: 1.20.1
  - contacts: 6.1.1
  - contactsinteraction: 1.11.0
  - dav: 1.31.1
  - deck: 1.14.2
  - dicomviewer: 2.2.1
  - drawio: 3.0.3
  - external: 5.5.2
  - federatedfilesharing: 1.20.0
  - federation: 1.20.0
  - files: 2.2.0
  - files_downloadlimit: 3.0.0
  - files_pdfviewer: 3.0.0
  - files_reminders: 1.3.0
  - files_sharing: 1.22.0
  - files_trashbin: 1.20.1
  - files_versions: 1.23.0
  - firstrunwizard: 3.0.0
  - impersonate: 1.17.0
  - logreader: 3.0.0
  - lookup_server_connector: 1.18.0
  - nextcloud_announcements: 2.0.0
  - notes: 4.11.0
  - notifications: 3.0.0
  - notify_push: 0.7.0
  - oauth2: 1.18.1
  - onlyoffice: 9.5.0
  - password_policy: 2.0.0
  - photos: 3.0.2
  - previewgenerator: 5.7.0
  - privacy: 2.0.0
  - provisioning_api: 1.20.0
  - serverinfo: 2.0.0
  - settings: 1.13.0
  - sharebymail: 1.20.0
  - support: 2.0.0
  - survey_client: 2.0.0
  - systemtags: 1.20.0
  - text: 4.1.0
  - theming: 2.5.0
  - theming_customcss: 1.17.0
  - twofactor_backupcodes: 1.19.0
  - twofactor_webauthn: 2.0.0
  - updatenotification: 1.20.0
  - viewer: 3.0.0
  - webhook_listeners: 1.1.0-dev
  - whiteboard: 1.0.4
  - workflowengine: 2.12.0
Disabled:
  - appointments: 2.2.0 (installed 2.2.0)
  - bookmarks: 15.0.2 (installed 15.0.2)
  - dashboard: 7.10.0 (installed 7.8.0)
  - encryption: 2.18.0 (installed 2.13.0)
  - files_external: 1.22.0 (installed 1.19.0)
  - files_fulltextsearch: 30.0.0 (installed 30.0.0)
  - fulltextsearch: 30.0.0 (installed 30.0.0)
  - fulltextsearch_elasticsearch: 30.0.0 (installed 30.0.0)
  - recommendations: 3.0.0 (installed 0.4.0)
  - related_resources: 1.5.0 (installed 1.1.0-alpha1)
  - richdocuments: 8.5.2 (installed 8.5.2)
  - suspicious_login: 8.0.0
  - twofactor_nextcloud_notification: 4.0.0
  - twofactor_totp: 12.0.0-dev
  - user_ldap: 1.21.0
  - user_migration: 7.0.1 (installed 7.0.1)
  - user_status: 1.10.0 (installed 1.5.0)
  - weather_status: 1.10.0 (installed 1.3.0)
```

**Nextcloud configuration:**

```
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "nextcloud.0x0c.de"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "skeletondirectory": "",
        "overwrite.cli.url": "https:\/\/nextcloud.0x0c.de",
        "dbtype": "mysql",
        "version": "30.0.2.2",
        "installed": true,
        "htaccess.RewriteBase": "\/",
        "maintenance": false,
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "dbpersistent": true,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "filelocking.enabled": true,
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 0,
            "dbindex": 0
        },
        "knowledgebaseenabled": false,
        "theme": "",
        "simpleSignUpLink.shown": false,
        "loglevel": 2,
        "log_authfailip": true,
        "mysql.utf8mb4": true,
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "sendmail",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpsecure": "ssl",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "updater.release.channel": "stable",
        "trashbin_retention_obligation": "auto, 30",
        "versions_retention_obligation": "auto, 180",
        "has_rebuilt_cache": true,
        "default_language": "de",
        "default_phone_region": "DE",
        "check_data_directory_permissions": false,
        "log_rotate_size": 52428800,
        "profile.enabled": false,
        "preview_max_x": 1920,
        "preview_max_y": 1920,
        "mail_sendmailmode": "smtp",
        "mail_smtpauth": 1,
        "mail_smtpport": "465",
        "trusted_proxies": "***REMOVED SENSITIVE VALUE***",
        "auth.bruteforce.protection.enabled": true,
        "ratelimit.protection.enabled": true,
        "reference_opengraph": true,
        "integrity.check.disabled": false,
        "defaultapp": "files",
        "maintenance_window_start": 2,
        "apps_paths": [
            {
                "path": "\/var\/www\/nextcloud.0x0c.de\/apps",
                "url": "\/apps",
                "writable": true
            }
        ],
        "app_install_overwrite": [
            "deck"
        ]
    }
}
```

**Are you using an external user-backend, if yes which one:** no

</details>

<details>
<summary>Logs</summary>

#### Nextcloud log (data/nextcloud.log)
```
(too large)
```

#### Browser log
```
Error with Permissions-Policy header: Unrecognized feature: 'browsing-topics'.
logger-Ba6Q6YnM.chunk.mjs:951 [WARN] viewer: Some mimes were ignored because they are not enabled in the server previews config {app: 'viewer', uid: 'awelzel', level: 2, ignoredMimes: Array(4)}
log @ logger-Ba6Q6YnM.chunk.mjs:951
warn @ logger-Ba6Q6YnM.chunk.mjs:951
(anonymous) @ viewer-init.mjs?v=7b18253f-81:4788
listener.js:184 [Deprecation] Listener added for a 'DOMNodeRemoved' mutation event. Support for this event type has been removed, and this event will no longer be fired. See https://chromestatus.com/feature/5083947249172480 for more information.
(anonymous) @ listener.js:184
(anonymous) @ listener.js:34
session-heartbeat.js:83 session heartbeat polling started
style-BNtK61kD.chunk.mjs:2 InvalidStateError: Failed to execute 'send' on 'WebSocket': Still in CONNECTING state.
    at IB (NotificationsApp-CX_2Ib0T.chunk.mjs:34:21826)
    at s.mounted (NotificationsApp-CX_2Ib0T.chunk.mjs:34:67268)
    at lt (style-BNtK61kD.chunk.mjs:2:23489)
    at tt (style-BNtK61kD.chunk.mjs:2:31208)
    at Object.insert (style-BNtK61kD.chunk.mjs:2:34641)
    at Ht (style-BNtK61kD.chunk.mjs:2:55281)
    at M.__patch__ (style-BNtK61kD.chunk.mjs:2:56635)
    at Gi.t._update (style-BNtK61kD.chunk.mjs:2:28791)
    at M.r (style-BNtK61kD.chunk.mjs:2:29561)
    at t.get (style-BNtK61kD.chunk.mjs:2:25766)
Ze @ style-BNtK61kD.chunk.mjs:2
qe @ style-BNtK61kD.chunk.mjs:2
St @ style-BNtK61kD.chunk.mjs:2
lt @ style-BNtK61kD.chunk.mjs:2
tt @ style-BNtK61kD.chunk.mjs:2
insert @ style-BNtK61kD.chunk.mjs:2
Ht @ style-BNtK61kD.chunk.mjs:2
(anonymous) @ style-BNtK61kD.chunk.mjs:2
Gi.t._update @ style-BNtK61kD.chunk.mjs:2
r @ style-BNtK61kD.chunk.mjs:2
t.get @ style-BNtK61kD.chunk.mjs:2
t.run @ style-BNtK61kD.chunk.mjs:2
Yi @ style-BNtK61kD.chunk.mjs:2
(anonymous) @ style-BNtK61kD.chunk.mjs:2
fn @ style-BNtK61kD.chunk.mjs:2
Promise.then
Gt @ style-BNtK61kD.chunk.mjs:2
ge @ style-BNtK61kD.chunk.mjs:2
oe @ style-BNtK61kD.chunk.mjs:2
t.update @ style-BNtK61kD.chunk.mjs:2
Gi.t.$forceUpdate @ style-BNtK61kD.chunk.mjs:2
s @ style-BNtK61kD.chunk.mjs:2
(anonymous) @ style-BNtK61kD.chunk.mjs:2
(anonymous) @ style-BNtK61kD.chunk.mjs:2
Promise.then
Pi @ style-BNtK61kD.chunk.mjs:2
nr @ style-BNtK61kD.chunk.mjs:2
Ti @ style-BNtK61kD.chunk.mjs:2
Sn @ style-BNtK61kD.chunk.mjs:2
t.$createElement @ style-BNtK61kD.chunk.mjs:2
render @ notifications-main.mjs?v=7b18253f-81:3
Ai.t._render @ style-BNtK61kD.chunk.mjs:2
r @ style-BNtK61kD.chunk.mjs:2
t.get @ style-BNtK61kD.chunk.mjs:2
t @ style-BNtK61kD.chunk.mjs:2
qi @ style-BNtK61kD.chunk.mjs:2
M.$mount @ style-BNtK61kD.chunk.mjs:2
t._init @ style-BNtK61kD.chunk.mjs:2
M @ style-BNtK61kD.chunk.mjs:2
(anonymous) @ notifications-main.mjs?v=7b18253f-81:3
```

</details>

**Comment by small1** [comment]
We are affected by that same bug.  Latest NC and Deck

**Comment by grnd-alt** [comment]
thanks a lot for your report. I could not yet reproduce the issue. How often does the focus issue occur relatively, does it happen every time the description is  saved or just some times?

**Comment by arnowelzel** [comment]
It happens some times. I edit 10 cards, at least 3-5 times this focus changes happens. My strategy to find the cause of this problem would be to check the code for the use of `focus()` - because without either removing the focus or setting it, this would not happen.

**Comment by q-wertz** [comment]
For me it always happens after the editor saved. So after typing and waiting for `Description (unsave)` to disappear focus is lost. This happens in bigger view as well as in sidebar view.

Also a lot of other actions currently remove the focus (all interactions with the Text menu). 

Maybe related: https://github.com/nextcloud/deck/issues/6550

**Comment by apoeteo** [comment]
@grnd-alt To me it's happening in the _sidebar view_ when mouse is not over the sidebar

**Steps to reproduce:**

1. Create a new card
2. (Switch to the sidebar view)
3. Type something and move the mouse away from the side bar
4. The focus is lost immediately, I don't even have to wait for autosave

It's happening every time
Not sure if it's intentional but for sure it's confusing

LibreWolf 134.0.1-1, Nextcloud AIO with Nextcloud Hub 9 (30.0.5), Deck 1.14.3

**Comment by ssolsu** [comment]
When using the Chrome browser and Windows 10 operating system with a Chinese input method (IME), the loss of focus occurs 100% of the time while editing in Nextcloud Deck. However, no such issue occurs when using an English input method.




> 非常感谢您的报告。我暂时无法重现该问题。焦点问题相对来说发生的频率是多少？每次保存描述时都会发生还是只发生几次？

**Comment by brianmichalk1** [comment]
I installed the High performance backend, and believe this bug is related to to interacting with push notifications.

**Comment by arnowelzel** [comment]
I also had the  High performance backend installed. I disabled it and will see, if that changes anything.

**Comment by q-wertz** [comment]
I tried to show the problem to a colleague and couldn't reproduce it.

5 minutes later it happened again (fortunately he was still there and could approve that I'm not going crazy ).

I also have the high performance backend enabled...

**Comment by arnowelzel** [comment]
I doubt, that the push service has anything to do with it, since this is most likely a frontend issue, and not a backend related.

As I already suggested: the code should be checked for any `focus()` calls which set the focus at all. I don't see any reason, why the frontend should set the focus anyway except once when opening a card for editing.

**Comment by arnowelzel** [comment]
Update: ok, I can now confirm, that indeed the push service seems to be involved.

Test case:

1. install and start the push service (also see https://arnowelzel.de/en/client-push-for-nextcloud)
1. create a new card in deck
2. open the card it for editing and type something in the description
3. wait until the card will be saved
4. see that the focus is lost and instead the title of the card gets the focus

And now the solution:

1. keep the deck card open for editing
2. stop the push service (`systemctl stop <push-service-name>`)
3. now edit the card description and wait again until it is saved automatically
4. now see that the focus is not lost

And to confirm that the push service does something here:

1. start the push service again (`systemctl start <push-service-name>`)
2. see the deck card editor loosing focus just right after the push service was started
3. OR: start typing in the deck card editor and then wait until it is saved automatically
4. see that the focus is lost and instead the title of the card gets the focus

I can reproduce this behaviour every time: as soon as the push service is started, the deck cards loose focus just in the moment, when the push notification is send in the background. It seems the frontend somehow get's triggered to update its view by the push service and this can cause the deck cards editor to loose focus.

So for the time being I keep my push service disabled. It was nice to have, but I can also live without it. Updates will just take a bit longer, but I don't have that many users on my Nextcloud instance, that polling of the clients will be an issue.

**Comment by tril0byte** [comment]
I had this problem and confirm it was fixed by running `sudo -u www-data -E php occ app:disable notify_push`

**Comment by Ornanovitch** [comment]
I also reproduced this!

**Comment by elek02** [comment]
Same here disable notify_push fixes the problem.

**Comment by Superjamp** [comment]
I wouldn't consider disabling notify_push a fix... 
thanks for bringing the issue to the notify_push repo :D https://github.com/nextcloud/notify_push/issues/580

**Comment by stereiss** [comment]
> thanks a lot for your report. I could not yet reproduce the issue. How often does the focus issue occur relatively, does it happen every time the description is saved or just some times?

@arnowelzel: Many thanks for the article - this behaviour annoys me every day, I've just been too lazy to report the issue!

@grnd-alt: This happens to me all the time - I can no longer edit cards without this error. For me, the focus changes when I stop typing for (what feels like) about a second - no long pause, no end of editing, no action with the mouse, etc.. I often type away and then realise that the focus has changed after the first word and I've typed everything into nirvana.

By the way: I use the client in the Vivaldi browser in Windows and no HPB.

**Comment by grnd-alt** [comment]
@arnowelzel thanks for your investigations, the hint to notify_push really did help me reproduce!
As the behavior seems to differ from person to person and between browsers there might be more to it then the small PR I did (though it resolved the issue for all I could reproduce) anyone can feel free to test the PR (or wait until it's eventually released) and report if there's still any issues regarding this.
