### ISSUE TITLE
Cannot connect from a new mobile device

### ISSUE THREAD

**Issue by sysprg1** [nextcloud/deck#6570]
App Version: 1.24.1
App Version Code: 1024001
Server App Version: 1.14.2
App Flavor: fdroid

Files App Version Code: 30290290 (PROD)

---

OS Version: 4.14.190-perf-28693687-abA525FXXSAFXJ2(A525FXXSAFXJ2)
OS API Level: 34
Device: a52q
Manufacturer: samsung
Model (and Product): SM-A525F (a52qnseea)

---

it.niedermann.nextcloud.deck.exceptions.OfflineException: Connection rejected
	at it.niedermann.nextcloud.deck.remote.api.ServerCommunicationErrorHandler$Handler.handle(ServerCommunicationErrorHandler.java:52)
	at it.niedermann.nextcloud.deck.remote.api.ServerCommunicationErrorHandler.translateError(ServerCommunicationErrorHandler.java:28)
	at it.niedermann.nextcloud.deck.remote.api.RequestHelper$ResponseConsumer.onFailure(RequestHelper.java:95)
	at it.niedermann.nextcloud.deck.remote.api.RequestHelper$ResponseConsumer.onResponse(RequestHelper.java:70)
	at com.nextcloud.android.sso.helper.Retrofit2Helper$1.lambda$enqueue$0(Retrofit2Helper.java:87)
	at com.nextcloud.android.sso.helper.Retrofit2Helper$1.$r8$lambda$n0izO5V3AflskH7z1H8dSLmVKXo(Unknown Source:0)
	at com.nextcloud.android.sso.helper.Retrofit2Helper$1$$ExternalSyntheticLambda0.run(Unknown Source:6)
	at java.lang.Thread.run(Thread.java:1012)

```

All OK in the web app. There are 3 boards, a new device got stuck on the 2nd board. 
I noticed, that some new tasks hadn't been seen on the other mobile phone. Opposite direction (from mobile phone to web) seemed to be always OK.

**Comment by juliusknorr** [comment]
Thanks for reporting this, from a first look this seems more like an issue with the Android app or the connectivity. Please report this at https://github.com/stefan-niedermann/nextcloud-deck
