### ISSUE TITLE
Upload atachements fail

### ISSUE THREAD

**Issue by digitalrevisor** [nextcloud/deck#6639]
```
App Version: 1.24.1
App Version Code: 1024001
Server App Version: 1.11.7
App Flavor: play

Files App Version Code: 30300690 (PROD)
Files App Version Code: 20241222 (DEV)

---

OS Version: 5.10.209-android12-9-29539737-abF936BXXU9GXK8(F936BXXU9GXK8)
OS API Level: 34
Device: q4q
Manufacturer: samsung
Model (and Product): SM-F936B (q4qxeea)

---

it.niedermann.nextcloud.deck.exceptions.UploadAttachmentFailedException: Unknown URI scheme
	at it.niedermann.nextcloud.deck.ui.card.attachments.CardAttachmentsFragment$5.onError(CardAttachmentsFragment.java:387)
	at it.niedermann.nextcloud.deck.remote.api.ResponseCallback$1.onError(ResponseCallback.java:76)
	at it.niedermann.nextcloud.deck.remote.helpers.DataPropagationHelper$1.lambda$onError$1(DataPropagationHelper.java:70)
	at it.niedermann.nextcloud.deck.remote.helpers.DataPropagationHelper$1$$ExternalSyntheticLambda1.run(Unknown Source:4)
	at it.niedermann.nextcloud.deck.util.ExecutorServiceProvider$RetryableRunnable.run(ExecutorServiceProvider.java:66)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:487)
	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)
Caused by: com.nextcloud.android.sso.exceptions.NextcloudHttpRequestFailedException: HTTP forespørsel feilet med status kode: 400
	at it.niedermann.nextcloud.deck.remote.api.RequestHelper$ResponseConsumer.onResponse(RequestHelper.java:70)
	at com.nextcloud.android.sso.helper.Retrofit2Helper$1.lambda$enqueue$0(Retrofit2Helper.java:87)
	at com.nextcloud.android.sso.helper.Retrofit2Helper$1.$r8$lambda$n0izO5V3AflskH7z1H8dSLmVKXo(Unknown Source:0)
	at com.nextcloud.android.sso.helper.Retrofit2Helper$1$$ExternalSyntheticLambda0.run(Unknown Source:6)
	... 1 more
Caused by: java.lang.RuntimeException: HTTP StatusCode wasn't 2xx:
Got [HTTP 400] for Call [GET http://localhost//index.php/apps/deck/api/v1.0/boards/272/stacks/859/cards/2453/attachments] with Message:
[{"status":400,"message":"type must be provided and must be not empty"}
]
	at it.niedermann.nextcloud.deck.remote.api.RequestHelper$ResponseConsumer.buildCause(RequestHelper.java:87)
	... 5 more

```

### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Client details:**
 - Device: [e.g. iPhone6, desktop]

<details>
<summary>Server details</summary>

**Operating system**:

**Web server:**

**Database:**

**PHP version:**

**Nextcloud version:** (see Nextcloud admin page)

**Where did you install Nextcloud from:**

**Signing status:**

```
Login as admin user into your Nextcloud and access
http://example.com/index.php/settings/integrity/failed
paste the results here.
```

**List of activated apps:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```

**Nextcloud configuration:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or

Insert your config.php content here
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

</details>

<details>
<summary>Logs</summary>

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```

</details>

**Comment by user8446** [comment]
`{"status":400,"message":"type must be provided and must be not empty"}`

You need to have `type=file` in the API call for adding an attachment.

**Comment by digitalrevisor** [comment]
Ok. But I use android and camera that is implemented in Dack app.

Med vennleg helsing

Roger Hopland

Statsautorisert revisor

Autorisert regnskapsfører


Digital Revisor AS


Naustdalsvegen 1B, 6800 Førde | Avdelinger - Bergen | Nordfjordeid | Måløy
*S:* +47 57824090 | *M:* +47 90077351 | *E:* ***@***.*** | *W:*
https://jointlyoffice.com/



ons. 1. jan. 2025 kl. 18:47 skrev Glenn Fowler ***@***.***>:

**Comment by juliusknorr** [comment]
This sounds a lot like https://github.com/stefan-niedermann/nextcloud-deck/issues/1689, I'll close this as a duplicate of the android app issue.

**Comment by digitalrevisor** [comment]
Android v 1.24.1 does not work on nc version 30 either. We have tested.

It works on iphone app Deck on NC version 27..

Bestill et møte med meg.
<https://demo.digitalrevisor.eu/apps/appointments/pub/Muj59JzyV0Lg4Zex4tu%2B2Q%3D%3D/form>

Med vennleg helsing

Roger Hopland

Statsautorisert revisor

Statsautorisert regnskapsfører

[image: RG_logoikon_e-post (2)]

Revisorgruppen Fjordane AS

Naustdalsvegen 1B, 6800 Førde | Avdelinger - Bergen | Nordfjordeid | Stryn |
Måløy
*S:* +47 57824090 | *M:* +47 90077351 | *E:* ***@***.*** | *W:* www.rg.no

[image: felles:Kunder:Revisorgruppen:UHY logos:UHY logo.eps]

Medlem av UHY International, en sammenslutning av uavhengige revisjons- og
konsulentselskaper


ons. 1. jan. 2025 kl. 18:47 skrev Glenn Fowler ***@***.***>:
